### ISSUE TITLE
[image] Split size attribute into size and computed_size

### ISSUE THREAD

**Issue by jaypif** [OpenNebula/terraform-provider-opennebula#104]
Problem:
Since resize is supported on VMs, the Image size can change during image lifecycle. However the `size` value of the resource image attached to the VM is not updated. This lead to a situation of delete / recreate image because the `size` is not the same.

Solution:
Use `size` of the image to be the "orignial size" of the image
Add a `computed_size` to reflect the size of the image on OpenNebula.

thanks to this solution, when an image is updated  the computed size is updated and it does not trigger a change on the VM

**Comment by treywelsh** [comment]
After some investigations on the problem: the `size` is not read by the provider in the image resource.

So yes, the image `size` won't be up to date after a disk resize (implemented in 0.3.0 version of the provider) on persistent image, but this won't trigger any harmful behavior, nothing will happen.

If we choose to implement this behaviour (read the image size), we'll need to take care to not introduce the problem stated above: the size attribute has `ForceNew` behaviour

Note on ONE behaviour: image persistence matters in case of disk resize: a non persistent image won't have it's size updated but a persistent image will have it's size updated

As usual I use minione to test with default configuration
