### ISSUE TITLE
[Virtula Machine] Remove Computed on Optionnal Fields

### ISSUE THREAD

**Issue by jaypif** [OpenNebula/terraform-provider-opennebula#106]
Better management of some Optional fields. If they are not provided as there are optional it must not result in an error

following Attributes are concerned:
- os
- cpumodel
- graphics

**Comment by treywelsh** [comment]
Two things changed here:
1. removal of unneeded `computed` behavior on attributes
2. reading behavior: attributes are read only when they are defined by the user 

By the way, a check has been added on `vmgroup` to only read it's content when defined in VM resource in tf file.

We want to avoid this case:
instantiating a VM with `template_id`, with a template that define some parts (`os`, `graphics`, `vmgroup` ...) that are not defined in the VM resource.

With `vmgroup` this is dangerous: it has `ForceNew` behaviour so the VM could be recreated.
