### ISSUE TITLE
Not authorized to perform USE GROUP [0].

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/terraform-provider-opennebula#111]
Hi, we have configuration when users do not belong default "Users" group in OpenNebula. Each user has his own group with own set of ACLs.

The problem is that when non admin user tries to create some resource, the following error returned:
```
[DEBUG] plugin.terraform-provider-opennebula_v0.3.0: 2021/03/23 16:44:04 [ERROR] Security group owner group change failed, error: OpenNebula error [AUTHORIZATION]: [one.secgroup.chown] User [4787] : Not authorized to perform USE GROUP [0].
```

To avoid this error, user must explicitly specify his group in the resource definition:

```diff
 # Security group
 resource "opennebula_security_group" "ssh" {
   name = "ssh-test"
   description = "Allow traffic only to port 22"
   permissions = "600"
+  group = "mygroup"
  
   # Inbound rules
   rule {
     protocol  = "TCP"
     rule_type = "INBOUND"
     range     = "22"
   }
   # Outbound rules
   rule {
     protocol  = "ALL"
     rule_type = "OUTBOUND"
   }
  
   tags = {
     environment = "common"
   }
 }
```

**Purposed solution:**
Do not use id=0 as default value for creating resources, use current user group instead.

**Comment by jaypif** [comment]
Hi @kvaps 

Actually only members of the `oneadmin` group are able to manage users and ACLs.
It is not allowed by Any other group to do this even if you give the ACL right to a group wich is not `oneadmin`

I already opened an issue at OpenNebula and they told me that limitation (`oneadmin` members only can manage ACLs) is in place for security reason and it won't change 

So in your case I am afraid you are limited to be part of Oneadmin group to perform what you want.

Regards

**Comment by kvaps** [comment]
Hi, @jaypif.

Thanks for details, but my case is slight different.

Actually I don't want to make any chown, but I force to specify group, otherwise the provider will try to chown resource to gid=0 and exceptionally will fail with the error.

**Comment by jaypif** [comment]
The provider use the primary group of the user which creates the resource

If the user you use to create resource has `oneadmin` (`gid = 0`) as primary group all resources are created with this group and then there is a chown to put the resource in the target group

The group must be crated prior to the resource with `opennebula_group` before.

Hope this help, Otherwise can you provide us the error you are facing ?

**Comment by kvaps** [comment]
> The provider use the primary group of the user which creates the resource

This is how it should be, but actually this statement is wrong, as my user does not belong to any `gid=0`

```xml
$ oneuser show 4787 -x
<USER>
  <ID>4787</ID>
  <GID>4577</GID>
  <GROUPS>
    <ID>4577</ID>
  </GROUPS>
  <GNAME>oc4790</GNAME>
  <NAME>oc4790</NAME>
```

Thus during the apply operation the resource is created with `gid=4577`, but after that operator tries to invoke chown for `gid=0` for some reason. This is confuses a lot.

**Comment by jaypif** [comment]
Ok what is the `gid` of the group `mygroup` ?
Does this group exists ?

If not the group id is set to 0.

I will take a look to check the error management in case the targeted group does not exist.

**Comment by kvaps** [comment]
The group is exists, has id `4577` this is main and only group which user belong (see the XML output above)

**Comment by jaypif** [comment]
The group name in the XML is `oc4790` not `mygroup`

Sorry I don't understand your point.

If I understand well you use the user `NAME = oc4790` with  `ID = 4787` member of the group `GNAME = oc4790` with `GID = 4577` to add a Security group resource `ssh-test`.
The permission for the resource is `600` wich means Owner manage, all other has no rights
You want to set the group to `mygroup` (I dont have the ID of this group).

In the documentation `mygroup` is not a keyword. It is an example of group name.
For the attribute `group` of you resource you should set the name of the group you want the resource to be part.
If you want the resource in your group you can remove this attribute.

Hope this helps

Regards

**Comment by kvaps** [comment]
Ok, I just replaced `oc4790` by `mygroup` in first output, sorry for confusing.

I don't want to set any group for the resource, but I have to because if group unspecified then terraform-provider will try to set gid=0 on it and expectially will fail because user has no rights for this.

**Comment by jaypif** [comment]
Oh I understand your last point. I will fix it

thanks

**Comment by kvaps** [comment]
Hey, there is also one bug found on OpenNebula, https://github.com/OpenNebula/one/issues/5315.
In combination with terraform-provider it is blocking VM creation requests with enough quota for the group.

Of course it should be fixed in core, but I think terraform-provider should not invoke one.vm.chown method in case if it is not really needed to avoid such problems on already existing installations,

**Comment by jaypif** [comment]
`group` is optional so you can remove the line in your resource. This means `chown` won't be call.

`group` must be specified only if you need to set a specific group for the resource otherwise it uses the caller primary group.

**Comment by kvaps** [comment]
Are you sure?
When group is not set, the terraform-opeator tries to set `group=0` instead.
So the method is still called.

**Comment by jaypif** [comment]
The chown is not performed if group is not specified on resource creation yes.

If the user which create the resource is member of group 0, the resource is created with this group.

**Comment by kvaps** [comment]
The original issue confirms that this statement is wrong.

Eg. my user **does not** belong to group 0, and when you try to create any resource with group unspecified, provider will try to invoke chown with group=0 for some reason.
