### ISSUE TITLE
Feature request: Allow upload image from terraform host for opennebula_image

### ISSUE THREAD

**Issue by CRASH-Tech** [OpenNebula/terraform-provider-opennebula#113]
subj

**Comment by frousselet** [comment]
Hello @CRASH-Tech,

Provisionning images is not on the scope of Terraform.
The best tool to do this is [Packer](https://www.packer.io). There is no official support yet but you can open an issue on [One](https://github.com/OpenNebula/one) to discuss about an OpenNebula plugin.

Thanks.
