### ISSUE TITLE
Do not require name for the resources

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/terraform-provider-opennebula#114]
Most of the resources can't be created without name attribute, while other cloud providers allowing doing this.
Terraform has statefile logic and the same code can be used to spawn multiple environments.
Each environment can have own set of resources with the computed names, which should not conflict with each other because of that.

```
Error: Missing required argument

  on main.tf line 34, in resource "opennebula_virtual_machine_group" "nonprod":
  34: resource "opennebula_virtual_machine_group" "nonprod" {

The argument "name" is required, but no definition was found.


Error: Missing required argument

  on main.tf line 47, in resource "opennebula_security_group" "ssh":
  47: resource "opennebula_security_group" "ssh" {

The argument "name" is required, but no definition was found.
```

**Comment by jaypif** [comment]
Hi @kvaps ,

The provider has been designed to follow OpenNebula's Logic. 
Some resource must have a valid name to be created, some others has a name provided by OpenNebula itself.

So Here it up to OpenNebula behavior not the provider.

**Comment by kvaps** [comment]
You're right, terraform provider should not include more logic than needed.
Thank you for explanation.
