### ISSUE TITLE
Image import: not all attributes imported (especially datastore_id, forcing replacement)

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/terraform-provider-opennebula#117]
I am trying to import some existing resources to terraform. I have the following section:

```
resource "opennebula_image" "myimage" {
    name             = "myimage"
    clone_from_image = 1229
    datastore_id     = 100
    persistent       = false
    permissions      = "660"
    group            = "mygrp"
}
```

Then imported the image using the following command:

```
terraform import opennebula_image.myimage 1281
```

However, when I run `terraform plan`, it wants to destroy and re-create the image, because there are no attributes `datastore_id` and `clone_from_image`, which both force replacement. There is no way how terraform would know which image this one has been cloned from (OpenNebula does not store this information), but at least the datastore id should be imported correctly instead of keeping this blank.

When I manually edit `terraform.tfstate` to match the `clone_from_image` and `datastore_id` attributes with the resource definition, `terraform plan` does not request the image to be recreated anymore, just edited in place, editing the `group`, `persistent`, and `timeout` attributes. I think opennebula provider should also import the `group` and `persistent` attributes, as those are set the same way in the imported image as in the resources description. There is `gname` attribute in `terraform.tfstate` with the correct group name, and `persistent: null`.

Thanks!

**Comment by jaypif** [comment]
Hi @Yenya 

`clone_from_image` is not relevant in case of importing an image. It is intended to clone an existing image. 
`datastore_id` forces the image recreation indeed. This is because when you create an image you have to specify the datastore_id. If you change it it delete / recreate the image. There no other way for the moment to migrate from 2 datastore an image.

So you are right importing an image with the provider is quite painful. The better way to use an existing image is to reuse its id with a data source.

**Comment by Yenya** [comment]
@jaypif: thanks for the reply.

What I am trying to do is to import the existing image, but be able to say e.g. `count=3` in the future, and have two more images created from the same base image as before. Or to be able to destroy the image and recreate it the same way. My use case is to get a generic OS image (say, preinstalled Fedora 33 minimal), and specialize it to some server role.

I am not trying to migrate the images between datastores - I have only one main datastore, in which the imported image resides. The problem is that importing the image does not fill in the datastore_id of the imported image at all, so later `terraform plan` thinks the image is being moved to a new datastore, while in fact it is not.

_The better way to use an existing image is to reuse its id with a data source._

This way I would not be able to create more images like this one in the future, do I understand it correctly?

Thanks,

-Yenya

**Comment by jaypif** [comment]
> This way I would not be able to create more images like this one in the future, do I understand it correctly?

You can. You can use the `clone_from_image` to create a new image based on the existing one.
You can get the image ID you want to clone via a data_source and use it in your new image.

You will create a new image based on the existing one.

It is what we do on our side. We have "based" image we never deploy them on prod. We create new ones each time by cloning them.

Regards
