### ISSUE TITLE
Prompt for a password and store a temporary token

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/terraform-provider-opennebula#121]
Hello,

is it possible for terraform to prompt for a user password to OpenNebula, get a temporary token (the same way as `oneuser login` does), and use it for subsequent connections, until it expires? I tried to use a working terraform setup, comment out the `password = "mypassword"` line, and run `terraform plan`:

```
$ terraform plan
provider.opennebula.password
  The password for the user

  Enter a value: mypassword          ← NOTE: the password was echoed on the terminal

╷
│ Error: Missing required attribute
│ 
│   on <input-prompt> line 1:
│   (source code not available)
│ 
│ The attribute "endpoint" is required, but no definition was found.
╵
╷
│ Error: Missing required attribute
│ 
│   on <input-prompt> line 1:
│   (source code not available)
│ 
│ The attribute "username" is required, but no definition was found.
╵
$
```
I would like to store the terraform configuration in Git, and obviously storing a user password there is not a good idea, and storing a temporary token is, well, temporary. Thanks,

-Yenya

**Comment by jaypif** [comment]
Hi,

You can use a token instead of a Password. 
But you have to create the token manually before.

The usersane must be set as requested by opennebula. Just replace the password by the token it shoud work.

Regards

**Comment by Yenya** [comment]
@jaypif - I am aware of that, I even tried using manually generated token myself, it worked. But the token is still sensitive information, which should preferably be kept outside of the git repo, outside of the terraform configuration. Moreover, the token is usually temporary, so putting it into git means it needs to be refreshed on a regular basis.

What I would like to have is
- prompt for a password if `password = ...` is not set in the main module (apparently Terraform is attempting to do this, but it does not work for some reason)
- use the password to obtain a temporary token
- store the token in .tfstate or somewhere
- use the token for subsequent requests, until it expires (then prompt for a password again)

Could this be done?

**Comment by jaypif** [comment]
Terraform Provider has not been designed to be smart for the moment.

So you might need to include terraorm usage after another tool which managed the token for exemple :
1. Script to generate the token, get the token and store it in a varaibale.tf file
2. run terraform
3. remove the variable.tf file for example.

This can be done in a CI/CD pipeline too.

To generate a token it means that the terraform user must have user management rights and then you have to use this new user to continue the workflow. This is quite dangerous too.

**Comment by frousselet** [comment]
Hello @Yenya,

This is not the role of Terraform.
A better way to do this is to use environment variables (after being generated outside of terraform):

```shell
export OPENNEBULA_PASSWORD=${token}
terraform apply
```

**Comment by jamie-pate** [comment]
It looks like the environment variable is broken in 1.3.1

│ Error: username should be defined
│ 
│   with provider["registry.terraform.io/opennebula/opennebula"],
│   on main.tf line 64, in provider "opennebula":
│   64: provider "opennebula" {
