### ISSUE TITLE
[Template] Add support for RAW

### ISSUE THREAD

**Issue by GnunuX** [OpenNebula/terraform-provider-opennebula#123]
I would like create a template that starts an UEFI image.
I need, in the template, something like:
```
RAW = [
  DATA = "
  <os firmware='efi'>
    <type>hvm</type>
    <loader secure='no'/>
  </os>
",
  TYPE = "kvm" ]
```

**Comment by treywelsh** [comment]
Link to the documentation of the RAW section of the template resource: https://docs.opennebula.io/5.12/operation/references/template.html?highlight=raw#hypervisor-section

This should be added to the template section of the Template resource.

**Comment by MEGrimshaw** [comment]
+1 Need this to access RNG & avoid entropy starvation on the VM's as OpenNebula doesn't currently support KVM RNG natively.

**Comment by jaypif** [comment]
Hi,

Until the new section "RAW" is available you can still use the deprecated "template" section to deploy templates with `RAW` section.

Regards
