### ISSUE TITLE
Create VROUTER

### ISSUE THREAD

**Issue by perrfect** [OpenNebula/terraform-provider-opennebula#140]
Need to create vRouter via terraform.
But the argument **vrouter = "YES"**, from the issue #32 in **opennebula_template** resource doesn't work.
`│ An argument named "VROUTER" is not expected here.`

**Comment by jaypif** [comment]
HI @perrfect 

The issue #32 is the issue for the Vrouter feature. 
It is not yet implemented as the feature is more complicated than expected so it took more time to implement. 

I will close this one as it duplicates #32. I don't know when the #32 will be done. 

Regards
