### ISSUE TITLE
Virtual machine resource strips Graphics block from template

### ISSUE THREAD

**Issue by maartendq** [OpenNebula/terraform-provider-opennebula#15]
We have a template that holds a graphics section for setting up a VNC for a new VM:
```
GRAPHICS = [
  LISTEN = "0.0.0.0",
  RANDOM_PASSWD = "YES",
  TYPE = "VNC" ]
```

We then define a resource "opennebula_virtual_machine" without a "graphics" parameter, but with a "template_id" parameter:

```
resource "opennebula_virtual_machine" "vm" {
  count       = var.vm_count
  name        = element(var.names, count.index)
  cpu         = var.cpu
  vcpu        = var.vcpu
  memory      = var.memory
  group       = var.group
  permissions = var.permissions
  template_id = var.template_id
  nic {
    model           = var.nic_model
    network_id      = var.nic_network_id
    security_groups = var.security_groups
  }
}
```

It appears the graphics part actually gets stripped of the VM afterwards, cause I don't see any graphics part anymore in the VM definition.

Let me know if you need any more information.
Thanks

**Comment by jaypif** [comment]
Hi,

This is clearly a bug. In the provider, for the moment, if the graphics is not filled in the resource declaration, it is force to an empty struct even if the Graphics is set in the template.

I will try to provide a fix soon.

**Comment by maartendq** [comment]
Hi @jaypif ,

Thanks! Same goes for the context part and maybe others too.

**Comment by jaypif** [comment]
PR #17 to fix this issue

**Comment by jaypif** [comment]
PR #17 merged.

Your issue is fixed now :)
