### ISSUE TITLE
Option for forcing VM to be recreated if Disk Image ID change

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/terraform-provider-opennebula#156]
**Description**

Currently, when we want to change the Disk's Image ID used by a VM, Terraform is simply updating the VM Disk ID, and it's doing a HotSwap of the VM Disk, making the VM crash, freeze or simply stops working correctly.

I believe this is because the Disk HotSwap functionality is not correctly supported by Linux, but it would be foolish to expect any OS to be able to handle HotSwap of the OS disk anyway.

**To Reproduce**

Deploy a VM with a specific Image ID with Terraform, then update the Image ID and re-run Terraform.

The VM will most likely reach the `RUNNING` state again, but the services running on it will not be working correctly anymore (i.e. Apache, Nginx, etc).

**Expected behavior**

I guess we could expect that Terraform should destroy the VM and recreate it with the new Image ID.

I guess we could also expect that there's a higher chance that the Disk Hot Swap functionality works if the VM is turned off, so maybe shutting down the VM first would be enough.

**Suggested fix**

Add an option in the `disk` section of the `opennebula_virtual_machine` Terraform Module to tell Terraform how to handle Image ID change :

```
disk {
    image_id    = var.image_id-vm1
    size        = var.disksize-vm1
    target      = "vda"
    driver      = "qcow2"
    on_change   = "restart" // Values: 'restart', 'recreate', 'swap'
}
```

**Details**
 - Terraform Provider Version: 0.3.0
 - Hypervisor: KVM
 - ONE Version: 6.0.0.2

**Additional context**
_None_

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by MEGrimshaw** [comment]
+1

**Comment by jaypif** [comment]
Hi @Th0masL,

Thanks for this issue. It sound good. We never faces such issue on our side but you are right it can happens.
We will take a look how to implement thisas disk change management is quite complex to keep disk order. 

My question is in case of several "disk" attache to a VM, if the "on_change" is not the same on several disk what should be done ?
IMHO, I propose to move the `on_disk_change` attribute to something general in the vm resource. It must be unique for a given VM.
Do you agree ?

**Comment by Th0masL** [comment]
Yes, I think you are right, it is reasonable to expect that this `on_disk_change` attribute should be defined at the VM level.

I think it would be quite complex to implement such functionality where there would be different `on_disk_change` attribute per multiple disks on the same VM.

**Comment by jaypif** [comment]
OK great we will think about adding this attribute at VM level.

I can't give you an ETA. Hopefully in a couple of month as we ahve a bunch of issues coming in the 0.4.0 but we need to update ou CI to chack everything is fine.

**Comment by Th0masL** [comment]
Thanks !

By the way, I would like to be able to help you and contribute more directly to the project, but I've been kinda struggling getting started with contributing because of lack of clear documentation about how to build things from source, how to enable debug/verbose messages, what are the requirements for the basic development setup, etc.

I'm not talking only about this Terraform Provider repo, but also with the `one` repo.

One of the thing I'm trying to do, for example, is to get the `one` ruby client/CLI build from source and working on MacOS.

Do you accept/want external contribution ? Is there a way to get more documentation on how to build/contribute to your repos ? Do you have a public Discord/Slack channel that I could join to make communication easier ?

**Comment by jaypif** [comment]
Hi, contribution are always welcome and we alredy merge updates and fixes from lots of people.
Actuelly @treywelsh and I are not part of OpenNebula. We developped the provider for aour need and we worked closely with openNebula to make it official with Terraform.

In terms of development rules we follow Terraform guide lines and try to respect them as much as we can. 
If you want to build the provider and use it with Terraform, you can follow this doc: https://www.terraform.io/docs/language/providers/requirements.html

About Slack / Discord: We use Slack in my company and we have a shared channel with OpenNebula. However it is not public. We can discuss with OpenNebula to  have a public channel to discuss about contribution.

**Comment by Th0masL** [comment]
Sounds good, thanks for the information ! And thank you so much for your work on the Terraform Provider !

My company is starting to use OpenNebula and we definitely rely on the Terraform Provider to be able to provision our infrastructure.

I'm on the SRE/DevOps side of the stack, and I'm not so good with Go, so sadly I can't contribute as much as I would like to, but my company will soon allocate some internal Dev resources to contribute to the Terraform Provider code.

One of the things that would tremendously help me, as a beginner in Go, would be to have more comments in the code, so I could more precisely understand what's going on, but I understand that those comments are probably not needed for people that already know how to write Go properly 😄

**Comment by danhigham** [comment]
All, please see my pull request (https://github.com/OpenNebula/terraform-provider-opennebula/pull/184) for a potential solution.
