### ISSUE TITLE
Add Datastore support

### ISSUE THREAD

**Issue by spuder** [OpenNebula/terraform-provider-opennebula#158]
Thank you for making this provider. 

There currently does not appear to be a way to specify which datastore that the provider should use. 

## API
https://github.com/OpenNebula/addon-nodejs

## CLI
https://github.com/OpenNebula/one/blob/master/src/cli/onevm#L608

## XML RPC
The variable is `ds_id`, if set to `-1` open nebula will automatically choose a datastore. 

https://docs.opennebula.io/doc/5.8/oca/ruby/OpenNebula/VirtualMachine.html

```
#deploy(host_id, enforce = false, ds_id = -1,, extra_template = "") ⇒ nil, OpenNebula::Error
```

We also tried creating a new ubuntu template with a non-default datastore and it generated this:

Note the addition of `SCHED_DS_REQUIREMENTS = "ID=\"0\""`

```
CONTEXT = [
  NETWORK = "YES" ]
CPU = "0.5"
DISK = [
  IMAGE = "bionic-server-cloudimg-amd64",
  IMAGE_UNAME = "oneadmin" ]
GRAPHICS = [
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
HYPERVISOR = "kvm"
INPUTS_ORDER = ""
LOGO = "images/logos/ubuntu.png"
MEMORY = "512"
MEMORY_UNIT_COST = "MB"
OS = [
  ARCH = "x86_64",
  BOOT = "" ]
SCHED_DS_REQUIREMENTS = "ID=\"0\""
VCPU = "1"
```

**Comment by treywelsh** [comment]
Hi,

Thank you for you issue.

The [Placement section attributes](https://docs.opennebula.io/5.12/operation/references/template.html#placement-section) are partially concerned in issue #26 and associated PR #154.
`SCHED_DS_REQUIREMENTS` is just a part that I didn't already enabled.

I close this issue but feel free to drop a comment in #26
