### ISSUE TITLE
multiple ar in opennebula_virtual_network

### ISSUE THREAD

**Issue by ahmadalli** [OpenNebula/terraform-provider-opennebula#183]
I've tried adding another `ar` to the `opennebula_virtual_network` while terraform shows it as new item, it'll then errors that the previous ar is in use indicating that it's trying to remove it

**Comment by treywelsh** [comment]
Yes the 0.3.0 release of the provider try to remove all ARs, then re-add ARs.
It's a bit violent and we tried to improve this in the 0.4.0 release of the provider via #141 

We still need to add some bug fixes the the 0.4.0 that we consider as a beta version but you can test it.
I close this issue for now but if you see any problem with the AR update from the 0.4.0 release feel free to open a new issue.
