### ISSUE TITLE
opennebula_template context update doesn't change anything

### ISSUE THREAD

**Issue by ahmadalli** [OpenNebula/terraform-provider-opennebula#187]
I've updated the `context.SSH_PUBLIC_KEY` section of my `opennebula_template` and it applied successfully but it didn't actually update the context of my template on the opennebula

**Comment by yerrysherry** [comment]
Indeed, I have the same problem.

Also, the documentation is wrong.

  context  {
    NETWERK = "YES"
  }

$ terraform validate
╷
│ Error: Unsupported block type
│ 
│   on modules/main.tf line 16, in resource "opennebula_template" "ontwikkel":
│   16:   context  {
│ 
│ Blocks of type "context" are not expected here. Did you mean to define argument "context"? If so, use the equals sign to
│ assign it a value.
╵

Changing to

  context = {
    NETWERK = "YES"
  }

This works.

**Comment by god7trong** [comment]
I have the same problem.
