### ISSUE TITLE
virtual_networks and "ar" parameter

### ISSUE THREAD

**Issue by puppetmaster** [OpenNebula/terraform-provider-opennebula#19]
I'm trying to use this provider and I follow the documentation but something is wrong with virtual_networks and "ar" parameter, maybe I missed something.

This is my resource : 

resource "opennebula_virtual_network" "devel" { 
      name = "devel" 
      permissions = "660" 
      group = "users"
      bridge = "${var.one_vswitch}" 
      vlan_id = "30"
      //physical_device = "eth0" 
      type = "ovswitch"                                                          
      mtu = 1500 
      gateway = "XXX.XXX.XXX.XXX"
      network_mask = "255.255.255.0"
      dns = "${var.cadoles_dns}"
      ar = [ { 
         ar_type = "IP4"
         size = "200"
         ip4 = "XXX.XXX.XXX.XXX" 
       } ] 
      clusters = [ "${var.cadoles_cluster_id}" ]
      security_groups = [ "0" ] 
 } 

And this is the answer of terraform plan : 

`Error: Unsupported argument

  on main.tf line 115, in resource "opennebula_virtual_network" "devel":
 115:     ar = [ { 

An argument named "ar" is not expected here. Did you mean "id"?`

I use Terraform v0.12.12 and I build the plugin from git repository branch "master".

**Comment by jaypif** [comment]
Hi @puppetmaster 

Can you try to declare `ar` like this:


```
resource "opennebula_virtual_network" "devel" {
name = "devel"
permissions = "660"
group = "users"
bridge = "${var.one_vswitch}"
vlan_id = "30"
//physical_device = "eth0"
type = "ovswitch"
mtu = 1500
gateway = "XXX.XXX.XXX.XXX"
network_mask = "255.255.255.0"
dns = "${var.cadoles_dns}"
ar {
ar_type = "IP4"
size = "200"
ip4 = "XXX.XXX.XXX.XXX"
}
clusters = [ "${var.cadoles_cluster_id}" ]
security_groups = [ "0" ]
}
```

Remove `= [` and closing `]`. I am sorry the wiki is not reflecting Terraform 0.12. I will change this. in the documentation

Since Terraform 0.12, paremeter using `TypeSet` should not be declared like list.

Regards

**Comment by puppetmaster** [comment]
Works great thank you
