### ISSUE TITLE
`opennebula_virtual_network_address_range`: Add support for IPAM driver

### ISSUE THREAD

**Issue by maartendq** [OpenNebula/terraform-provider-opennebula#192]
In opennebula you can define an IPAM driver (at creation only) in the address range of a virtual network.
Is it possible to add this to the virtual network resource in terraform?

**Comment by frousselet** [comment]
Documentation: https://docs.opennebula.io/6.4/integration_and_development/infrastructure_drivers_development/devel-ipam.html

**Comment by treywelsh** [comment]
If I understand right the documentation, from provider point of view it's only about enabling a `IPAM_MAD` in the vnet address ranges.

However the attribute is not documented in https://github.com/OpenNebula/one/blob/master/share/doc/xsd/vnet.xsd and then Goca doesn't know this attribute.
I opnened a PR to fix this: https://github.com/OpenNebula/one/pull/6020

We'll then need to update the provider dependency on goca to be able to use this

**Comment by treywelsh** [comment]
I closed https://github.com/OpenNebula/one/pull/6020 and submitted https://github.com/OpenNebula/one/pull/6055 instead, which is more generic and will also help for #376

**Comment by treywelsh** [comment]
EDIT: the PR mentioned in previous comment introduced a regression in Goca, I submitted a new PR to fix this: https://github.com/OpenNebula/one/pull/6104
