### ISSUE TITLE
FILES_DS '\"' is unescaped

### ISSUE THREAD

**Issue by epolovina** [OpenNebula/terraform-provider-opennebula#196]
Some of our templates use FILES_DS in the context field and they contain something like 
```sh
FILES_DS = "$FILE[IMAGE=\"file.sh\", IMAGE_UNAME=\"oneadmin\"]"
```

Terraform plan works as expected but when doing apply the following error results:
```sh
Error: OpenNebula error [INTERNAL]: [one.template.instantiate] Parse error: syntax error, unexpected VARIABLE, expecting COMMA or CBRACKET at line 5, columns 127:134
```

Temporary fix is to manually override the context field and escape the '\\' accordingly
```sh
FILES_DS = "$FILE[IMAGE=\\\"file.sh\\\", IMAGE_UNAME=\\\"oneadmin\\\"]"
```

**Comment by rockpapergoat** [comment]
@epolovina in your example here, does the `$FILE` portion get evaluated/expanded to some value?
`FILES_DS = "$FILE[IMAGE=\\\"file.sh\\\", IMAGE_UNAME=\\\"oneadmin\\\"]"`

i need to do roughly the same thing. in templates that folks have manually created, the `$FILE` variable appears as typed. when i applied my terraform to create templates and such, the value ends up evaluated. does that seem right?

**Comment by erypolovina** [comment]
That seems right.
