### ISSUE TITLE
 Terraform updating in place even when no changes introduced to resource

### ISSUE THREAD

**Issue by jaypif** [OpenNebula/terraform-provider-opennebula#2]
Previously created here: https://github.com/OpenNebula/terraform-provider-opennebula/issues/42

___________________________________________

Whenever I run terraform plan/apply, terraform always wants to update the vm in place even though there have been no changes from me.

I removed the graphics section completey from my template or my resource but terraform still wants to change the vm in place (graphics):

```
~ resource "opennebula_virtual_machine" "vm_" {
        cpu         = 4
        gid         = 0
        gname       = "oneadmin"
        id          = "154"
        instance    = "test-slv-07"
        ip          = "10.71.155.13"
        lcmstate    = 3
        memory      = 4096
        name        = "liveops-test-slv-07"
        pending     = false
        permissions = "600"
        state       = 3
        template_id = 26
        uid         = 4
        uname       = "deployer"
        vcpu        = 4

        disk {
            driver   = "raw"
            image_id = 4
            size     = 102400
            target   = "vda"
        }

      - graphics {}

        nic {
            ip              = "10.71.155.13"
            mac             = "XX"
            network         = "Network"
            network_id      = 0
            nic_id          = 0
            security_groups = [
                0,
            ]
        }

        os {
            arch = "x86_64"
            boot = "disk0"
        }
```

Also I am seeing the same issue when creating templates. It updates in place the templates even when there are no changes.

**Comment by histrio** [comment]
Hi,
The issue described here https://github.com/OpenNebula/terraform-provider-opennebula/issues/42#issuecomment-559473492 still happens. I've tried to install release (provider.opennebula: version = "~> 0.1") and build it from the master branch but no luck.

**Comment by jaypif** [comment]
Hi @histrio 

Can you retry with #11  ?
I found the fix for this annoying issue.

Regards

**Comment by treywelsh** [comment]
Seems ok to me: when first call to `apply` is successful, the second call to `plan` or `apply` display:  
```No changes. Infrastructure is up-to-date.```

**Comment by histrio** [comment]
It works now. Thanks!
