### ISSUE TITLE
Documentation Various issues and old goca

### ISSUE THREAD

**Issue by jaypif** [OpenNebula/terraform-provider-opennebula#20]
Under HTML doc there are still:
* Formatting issues (markdown or typos)
* Deprecated Terraform syntax (before 0.12) examples

**Comment by turb0steve** [comment]
I have a few updates to the data provider markdown I can contribute, if it helps?
It's just from my own notes - not likely to set the world on fire 😄.
[ONebTF  Data Provider.zip](https://github.com/terraform-providers/terraform-provider-opennebula/files/4474544/ONebTF.Data.Provider.zip)

I'll be updating these anyway as I work with them, so happy to share?
