### ISSUE TITLE
[virtual_networks] impossible to add new AR

### ISSUE THREAD

**Issue by w1llrock** [OpenNebula/terraform-provider-opennebula#225]
Hi, when I try to add a new AR range, I get an error:

opennebula_virtual_network.vlan500: Modifying... [id=1]
╷
│ Error: OpenNebula error [INTERNAL]: [one.vn.rm_ar] Address Range has leases in use
│ 
│   with opennebula_virtual_network.vlan500,
│   on networks.tf line 19, in resource "opennebula_virtual_network" "vlan500":
│   19: resource "opennebula_virtual_network" "vlan500" {
│ 
╵
ERRO[0008] 1 error occurred:
        * exit status 1

Terraform provider: 0.3.0
Openebula: 6.0.0.3

**Comment by jaypif** [comment]
Hi,

The error says `Address Range has leases in use` it means you try to update an existing Address range with IP already in use in it not adding a new one.

Can you share the entire network resource configuration please ?

Thank you

**Comment by w1llrock** [comment]
Default configuration for network resource:

resource "opennebula_virtual_network" "vlan500" {
  name            = "10.145.70.0_vlan500"
  type            = "802.1Q"
  guest_mtu       = 1500
  clusters        = [100]
  bridge          = "br500"
  physical_device = "bond0"
  mtu             = 1500
  vlan_id         = "500"
  dns             = "10.145.70.254"
  gateway         = "10.145.70.1"
  security_groups = [0]
  ar {
    ar_type = "IP4"
    ip4     = "10.145.70.30"
    size    = 6
  }
}

Сhanged configuration :

resource "opennebula_virtual_network" "vlan500" {
  name            = "10.145.70.0_vlan500"
  type            = "802.1Q"
  guest_mtu       = 1500
  clusters        = [100]
  bridge          = "br500"
  physical_device = "bond0"
  mtu             = 1500
  vlan_id         = "500"
  dns             = "10.145.70.254"
  gateway         = "10.145.70.1"
  security_groups = [0]
  ar {
    ar_type = "IP4"
    ip4     = "10.145.70.30"
    size    = 6
  }
  **ar {
    ar_type = "IP4"
    ip4     = "10.145.70.90"
    size    = 6
  }**
}

Does this mean that if you need to add another range using terraform, I can't do it? Because from cli/gui everything works fine.

**Comment by jaypif** [comment]
Hi @w1llrock 

In the relase 0.3.0 adding an AR (or updating an existing one) is not well manage: We delete all AR to recreate them. That is why you are facing an error because you have IPs used in the first Range.
You are right, what you want to do works fine in CLI / Sunstone. 

This is a know issue fixed in the 0.4 release of the provider. This release is in Beta test, the last RC is 0.4.1. You can test it to confirm this release solve your issue.

Sorry for the incovenience

**Comment by w1llrock** [comment]
Hi Jaypif
I'll try to test the 0.4 version and wait for the new release. 
Thanks for the information!
