### ISSUE TITLE
Creating user as group admin for created group - chicken/egg problem?

### ISSUE THREAD

**Issue by kepi** [OpenNebula/terraform-provider-opennebula#228]
Hi,

I'm not sure if I'm missing something obvious, but I want to create new user and group in OpenNebula. And set that new user as admin for created group.

From documentation, only possibility seems to be something like this: 

```hcl
resource "opennebula_group" "group" {
  name                  = "example"
  admins               = [opennebula_user.user.id]
  template              = <<EOT
SUNSTONE = [
  DEFAULT_VIEW = "cloud",
  GROUP_ADMIN_DEFAULT_VIEW = "groupadmin",
  GROUP_ADMIN_VIEWS = "cloud,groupadmin",
  VIEWS = "cloud"
]
EOT
  delete_on_destruction = true
}

resource "opennebula_user" "user" {
  name          = "example"
  password      = random_password.password.result
  auth_driver   = "core"
  primary_group = opennebula_group.group.id
}

```

But problem is, that:

1. I can't create user with primary group which doesn't exist.
2. And I can't create group with admin which doesn't exist... 
 
I tried to work around this with `data` instead of `resource`. And I also tried adding *ACL* instead of setting user as primary, but that doesn't work at least for *Sunstone*.

I suppose one possibility at the moment might be using different group as primary and use obsolete `users` in `opennebula_group`. But as this is obsoleted, this wont be working in future. I would also like to have user only in single (primary) group.

From quick glance, it would be best to add something like `group_admin_for` array in `opennebula_user`.

Edit: using 0.4.1 provider

**Comment by jaypif** [comment]
Hi,

You are right you cannot create 2 resources which need each other to work. You need to perform this in 2 steps.
We decided to remove the "users" part because of this cyclic redundancy.

In your case, the best way is to do this in two times:
1. Create the user
2. Create the group with previous user as admin and update the primary group of this user.

We will take a llok deeper in a best way to do this. We need to manage this 2 resource without dependency

Thanks

**Comment by kepi** [comment]
By two-times you mean two terraform directories, two states etc? That would be beating all pros of terraform, but I'll probably try that as workaround until better way is found.

I have no deep knowledge of either OpenNebula or Terraform, but some more thinking about this more, I still believe that `group_admin_for` (or some better name like `admin_for_groups` maybe) in `opennebula_user` can be working just fine and would not lead to cyclic dependency.

Second approach might be to introduce new resource, something like `opennebula_group_admin`...

**Comment by jaypif** [comment]
By 2 times I mean

1. Create the user (1st apply)
2. update the TF file to add the group, add previous user as admin and set this group as primary for the user (2nd apply)

Hope this is clear.

**Comment by frousselet** [comment]
Hello,

I think the idea @kepi mentioned of creating a new resource `opennebula_group_admins` (with a 's') is the good approach:

```hcl
resource "opennebula_group" "group" {
  name                  = "example"
  template              = <<EOT
SUNSTONE = [
  DEFAULT_VIEW = "cloud",
  GROUP_ADMIN_DEFAULT_VIEW = "groupadmin",
  GROUP_ADMIN_VIEWS = "cloud,groupadmin",
  VIEWS = "cloud"
]
EOT
  delete_on_destruction = true
}

resource "opennebula_user" "user" {
  name          = "example"
  password      = random_password.password.result
  auth_driver   = "core"
  primary_group = opennebula_group.group.id
}

resource "opennebula_group_admins" "admin_attachment" {
  group = opennebula_group.group.id
  users = [
    opennebula_user.user.id
  ]
}
```

With this option, the `admins` attribute from `opennebula_group` should be flagged as `DEPRECATED`.

Added in the 0.5.0 milestone.
