### ISSUE TITLE
Templates always update even without changes.

### ISSUE THREAD

**Issue by benosman** [OpenNebula/terraform-provider-opennebula#23]
I'm using the template resource and have found it impossible to get the resource to pass through a `terraform apply` without updating.

I've updated to the latest changes in master, and at first I experienced whitespace issues which were giving false positives. After fixing those, the diff shows no actual differences in the template but still requires an update.

I even used a template data source and passed in the very same template but it still updates each time.

Looking at the code, it's clear that there it is just a simple string comparison, so it is no real suprise it doesn't work reliably. 

I noticed there was talk in another issue of creating a schema for the template which would help, but if passing a string in as a template is to be retained, there should be a way of normalising the template to avoid whitespace differences affecting the comparison.

#15

**Comment by treywelsh** [comment]
@benosman 

The PR being merged, feel free to open a new issue is you see any other problem

Thank you :)
