### ISSUE TITLE
VXLAN automatic_vlan_id

### ISSUE THREAD

**Issue by nimbus-tech** [OpenNebula/terraform-provider-opennebula#23]
Hi,

When I set automatic_vlan_id = true, we are getting below error

	* opennebula_virtual_network.XXXXX: OpenNebula error [INTERNAL]: [one.vn.allocate] VLAN_ID (or AUTOMATIC_VLAN_ID) is mandatory for driver vxlan

setting up manual vxlan_id works. we dont want to set vxlan id manually since its another task to manage it.
Also attached the tf file. hope its enough for you to check. 
[network.txt](https://github.com/OpenNebula/terraform-provider-opennebula/files/3822891/network.txt)

**Comment by jaypif** [comment]
OK I able to reproduce your issue.

**Comment by jaypif** [comment]
I found the issue.
 #37 fixes it
