### ISSUE TITLE
Compatibility darwin_arm64 (Apple Silicon M1)

### ISSUE THREAD

**Issue by carlosjsanch3z** [OpenNebula/terraform-provider-opennebula#230]
Hi!

Is there any intention to add support for the **darwin_arm64** architecture in future versions?

Error:
```bash
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/opennebula/opennebula v0.4.2 does not have a package
│ available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are
│ available for all platforms. Other versions of this provider may have different
│ platforms supported.
```
Thanks,
Greetings.

**Comment by jaypif** [comment]
Hi,

Thank you for opening this issue.
We will take a look to build a release for this architecture.

I keep you updated

**Comment by jaypif** [comment]
Should be fixed by #231

**Comment by jaypif** [comment]
HI @carlosjsanch3z 

We deployed a new release of the provider 0.4.3 (same as 0.4.2) with darwin ARM 64 compatibility

Can you confirm this is OK for  you ?

**Comment by carlosjsanch3z** [comment]
Hey @jaypif,

I can confirm that it now works correctly :)

Thank you very much for the quick solution.

**Comment by jaypif** [comment]
Excellent. Thanks
