### ISSUE TITLE
[resource][`opennebula_group`] `template` attribute

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#248]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During #161 development I add some trouble to avoid some diffs on the `template` attribute of the `opennebula_group` resource, which make me consider to open this issue (first goal was to migrate to the last SDK, not refactoring).
The goal of this attribute is to customize the template of the `opennebula_group` resource.

The `template` attribute in `opennebula_group` resource allow to pass either some XML, or a custom ONE format.
This kind of attribute have some downsides:
- big and complex string, several possible formats to handle
- invisible changes (spaces, tab, newline...) are seen by terraform as a diff

XML format is not easily readable, and the ONE format is a complex string formatted according to the [rules described here (for ONE release 6.0)](https://docs.opennebula.io/6.0/management_and_operations/references/template.html#syntax).

It's possible to improve how we work with a template string with some additional work. I'll describe this in a proposal below.

To help users to understand what's the template section in OpenNebula resources: it's a dynamic section that may contains:
- some flat `key = value` elements (that I call pair)
- some elements with one level of nesting: `vector_key = [ key1 = value1, ... ]`  (that I'll call vector)
The template may mix elements from OpenNebula, some user defined resource configuration, and fully custom elements provided by the user.
There is sometimes some specificities per resource type, like key unicity etc.

It's why the string attribute was convenient to describe a template: there is no limit in the description if the syntax is accurate.
It's not possible to represent this in the provider via a single schema attribute due to the level of nesting.

From here are some proposals to improve the template management in the `opennebula_group` resource:
- deprecate template and add at least two sections:
   - a section with TypeMap type that manage flat elements (named `tags` in other provider resources)
   - either an other section with TypeMap nesting that dynamically manage the vectors, or like we did in other resources until now, a static section per vector we want to manage (i.e. for the group we could add a `sunstone` section with TypeSet type).
   TypeMap nesting would be more generics but we need to if TypeMap nesting is available for the SDK versions we use (not possible in early versions of the SDK)
- write a ONE format parser that parse and reformat the string before giving it to the provider
  I tried this solution and it works  (I wanted to be able to parse the template format anyway) .

First solution should be better, we'll need to make a choice regarding other resources for consistency etc.

### New or Affected Resource(s)

- opennebula_group

In the future we may want to make evolve some other resources like opennebula_user that has no template management at all, or even other resource for consistency

### Potential Terraform Configuration

Here how a group config looks like for now:

```hcl
resource "opennebula_group" "group" {
  name = "iamgroup"
  template = <<EOF
    SUNSTONE = [
      DEFAULT_VIEW = "cloud",
      GROUP_ADMIN_DEFAULT_VIEW = "groupadmin",
      GROUP_ADMIN_VIEWS = "cloud",
      VIEWS = "cloud"
    ]
    EOF
    delete_on_destruction = true
}
```

This may be instead something like (if we choose the semi-dynamic way to do):
```hcl
resource "opennebula_group" "group" {
  name = "iamgroup"
  tags = { ... }
  sunstone = {
      DEFAULT_VIEW = "cloud",
      GROUP_ADMIN_DEFAULT_VIEW = "groupadmin",
      GROUP_ADMIN_VIEWS = "cloud",
      VIEWS = "cloud"
  }
  delete_on_destruction = true
}
```

#### References

[Groups optional configuration via template](https://docs.opennebula.io/5.12/operation/users_groups_management/manage_groups.html#group-wise-configuration-attributes)

**Comment by frousselet** [comment]
This is a very (very) good proposal! 🤩
Thanks for the clear explanations and investigation!
