### ISSUE TITLE
Terraform plugin sdk is out of date?

### ISSUE THREAD

**Issue by bsanders** [OpenNebula/terraform-provider-opennebula#254]
While investigating #252, I noticed that this code currently pins 1.7.0 of the hashicorp terraform plugin sdk.  It appears that the 1.x series is EOL (no bugfixes, etc) [0].  Is that on the team's radar?  Are there any plans for moving that forward?  I'm pretty new to golang/terraform, so I'm not entirely clear how much of a lift that would be.  I know there was mention of some refactoring being done in a PR, but not sure what the scope of that was.

[0] - https://github.com/hashicorp/terraform-plugin-sdk/blob/v1-maint/SUPPORT.md

**Comment by frousselet** [comment]
Hi @bsanders,

Migration to `SDK v2` is planed for the 0.5.0 release.
Please refer to #137 (issue) and #161 (PR) for updates.

If you want to work directly with the `SDK v2`, you can pull the branch `treywelsh:sdk-migration-v2` and merge your PR on it.
Or you can stay on `SDK v1` for now and we will migrate it to `SDK v2` then.

Thanks.

**Comment by treywelsh** [comment]
#161 was just merged, we now use the SDK v2.10.1, you can work on top of master now

**Comment by bsanders** [comment]
Thanks @treywelsh!
