### ISSUE TITLE
Add template and VM schemas

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#26]
As proposed in this comment: https://github.com/OpenNebula/terraform-provider-opennebula/pull/24#discussion_r377229103

We could add some new schemas parts for VM and template resources.

Draft proposal:

We could add the field `description` on both (but also on images... etc)

Add to Template resource:
- `hypervisor`
- `sched_requirements`
- `user_inputs`

EDIT: an user asked for an other [placement section attribute](https://docs.opennebula.io/5.12/operation/references/template.html#placement-section):
- `shed_ds_requirements`

Feel free to drop a comment to update this list

**Comment by trenton42** [comment]
I'm not sure if I missed it, but I think the User Template section is also missing on VMs

**Comment by treywelsh** [comment]
The UserTemplate part is managed through the _tags_ schema for now :)
In fact, the tags schema was added to manage custom key, value pairs (So tags may manage a subset of the UserTemplate part in the future).
However, there is a limitation, only key, value pairs are managed, not custom vectors.

**Comment by trenton42** [comment]
Thank you! That is helpful :+1:

**Comment by perrfect** [comment]
Hello.
How correctly use USER_INPUTS?
I do:
```
  user_inputs = {
    ROLE = "M|text|ANSIBLE_ROLE| |"
  }
```
But I've got an error:
`Blocks of type "user_inputs" are not expected here.`

**Comment by treywelsh** [comment]
The user inputs part is not managed by the provider for now, but PR #154 will enable it
