### ISSUE TITLE
`opennebula_virtual_network`: Terraform says read-only `id` and `computed_mac` changed outside of Terraform

### ISSUE THREAD

**Issue by frousselet** [OpenNebula/terraform-provider-opennebula#263]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- `opennebula_virtual_network`

### Terraform Configuration Files

```hcl
resource "opennebula_virtual_network" "example" {
    name            = "example"
    permissions     = "660"
    group           = opennebula_group.group.name
    bridge          = "br0"
    physical_device = "eth0"
    type            = "fw"
    mtu             = 1500
    dns             = "172.16.100.1"
    gateway         = "172.16.100.1"
    security_groups = [ 0 ]
    ar {
         ar_type = "IP4"
         size    = 16
         ip4     = "172.16.100.101"
    }
    clusters {
        id = 0
    }
    tags = {
      environment = "dev"
    }
}
```

### Expected Behavior

Terraform should ignore change `opennebula_virtual_network.example.ar.id` and `opennebula_virtual_network.example.ar.computed_mac` (and any other computed attribute) during `terraform plan` or `terraform apply`. These attributes are read-only.

### Actual Behavior

Terraform recreates `opennebula_virtual_network.ar` for each deployment since it find changes on `opennebula_virtual_network.example.ar.id` and `opennebula_virtual_network.example.ar.computed_mac`.

```shell
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
  # opennebula_virtual_network.example has been changed
  ~ resource "opennebula_virtual_network" "example" {
        id              = "86"
        name            = "example"
        tags = {
          environment = "dev"
        }
        # (17 unchanged attributes hidden)
      + ar {
          + ar_type      = "IP4"
          + computed_mac = "aa:bb:cc:dd:ee:ff"
          + id           = "0"
          + ip4          = "172.16.100.101"
          + size         = 16
        }
      - ar {
          - ar_type = "IP4" -> null
          - ip4     = "172.16.100.101" -> null
          - size    = 16 -> null
        }
    }
```

### Steps to Reproduce

1. `terraform plan`

**Comment by treywelsh** [comment]
This happens when creating the resource with the 0.3.0 release of the provider, then making a plan with a higher release (currently 0.4.3 and 0.5.0).
From 0.4.x releases new attributes have been introduced, I think it's why terraform show this diff.

In addition, the diff shown above is under the section `Note: Objects have changed outside of Terraform`
Then below:
```
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```
So this shouldn't trigger any unexpected update.

**Comment by frousselet** [comment]
I close this issue since `ar` will be deprecated on the 1.0.0 (see #279).
