### ISSUE TITLE
[Virtual Machine] some configuration parts can't be updated 

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#27]
For VM resources, we could allow to udpate configuration parts:

- graphics
- os
- context (taking care to not erase the whole context)
- tags

Note: for VMs there is two RPC vm update method regarding the part to update.

**Comment by jaypif** [comment]
Hi,

tags update is already supported

For other stuff it is more complicated as it depends on lots of stuffs

**Comment by benendboss** [comment]
i try to make changes on my vm's like gaining more memory and the apply goes trough with successfully changes but nothing happen to the vm/template

`module.vm.opennebula_virtual_machine.vm[0]: Refreshing state... [id=778]                                                                                                                       
                                                                                                                                                                                               
An execution plan has been generated and is shown below.                                                                                                                                       
Resource actions are indicated with the following symbols:                                                                                                                                     
  ~ update in-place                                                                                                                                                                            
                                                                                                                                                                                               
Terraform will perform the following actions:                                                                                                                                                  
                                                                                                                                                                                               
  # module.vm.opennebula_virtual_machine.vm[0] will be updated in-place                                                                                                                        
  ~ resource "opennebula_virtual_machine" "vm" {                                                                                                                                               
        cpu         = 1                                                                                                                                                                        
        gid         = 0                                                                                                                                                                        
        gname       = "oneadmin"                                                                                                                                                               
        group       = "oneadmin"                                                                                                                                                               
        id          = "778"                                                                                                                                                                    
        ip          = "XXXX"
                                                                                                                                                         
        lcmstate    = 3                                                                                                                                                                        
      ~ memory      = 1024 -> 2048                                                                                                                                                             
        name        = "XXXX"
                                                                                                                                                             
        pending     = false                                                                                                                                                                    
        permissions = "660"                                                                                                                                                                    
        state       = 3                                                                                                                                                                        
        tags        = {                                                                                                                                                                        
            "environment" = "stage"                                                                                                                                                            
        }                                                                                                                                                                                      
        timeout     = 5                                                                                                                                                                        
        uid         = 17                                                                                                                                                                       
        uname       = "XXXX"                                                                                                                                                        
        vcpu        = 1  
        disk {
            driver   = "qcow2"
            image_id = 18
            size     = 20000
            target   = "vda"
        }

        graphics {
            keymap = "de"
            listen = "XXXX"
            port   = "XXXX"
            type   = "vnc"
        }

        nic {
            ip              = "XXXX"
            mac             = "XXXX"
            model           = "virtio"
            network         = "XXXX"
            network_id      = 1
            nic_id          = 0
            physical_device = "bond0"
            security_groups = [
                0,
            ]
        }

        os {
            arch = "x86_64"
            boot = "disk0"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vm.opennebula_virtual_machine.vm[0]: Modifying... [id=778]
module.vm.opennebula_virtual_machine.vm[0]: Modifications complete after 0s [id=778]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
`
After this change nothing happened on the vm in opennebula

**Comment by treywelsh** [comment]
I didn't mentioned important parts that we may want to update on a running/powered off VM... like disk, NIC.
I opened new issues to track current proposal on:
- VM disk update: #64
- VM nic update: #72
