### ISSUE TITLE
Fix code scanning alert - Incorrect conversion between integer types

### ISSUE THREAD

**Issue by frousselet** [OpenNebula/terraform-provider-opennebula#278]
Tracking issue for:
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/1
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/2
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/3
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/4
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/5
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/6
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/7
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/8
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/9
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/10
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/11
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/12
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/13
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/14
- [ ] https://github.com/OpenNebula/terraform-provider-opennebula/security/code-scanning/15

**Comment by treywelsh** [comment]
EDIT:

All the errors are about type casting from `int64` to `int`.
I'm asking myself it I could just propose a quick fix for ParseInt, ParseUint methods:

My understanding of the `int` type behavior:
```The int, uint, and uintptr types are usually 32 bits wide on 32-bit systems and 64 bits wide on 64-bit systems.```

And from the [ParseInt documentation](https://pkg.go.dev/strconv#ParseInt):
```
The bitSize argument specifies the integer type that the result must fit into. Bit sizes 0, 8, 16, 32, and 64 correspond to int, int8, int16, int32, and int64. If bitSize is below 0 or above 64, an error is returned.
```
If I use the `0` bit size, I expect the ParseInt method to fails if it tries to parse a 64 bits integer on a 32 bit system (i.e. int stored on 32 bits) on the system the provider is running (However I'll need to read the `ParseInt` source code to be sure).

**Comment by treywelsh** [comment]
Downside: provider may not work on 32 bits systems, but in a cleaner way (i.e. would raise an expected error)
