### ISSUE TITLE
Upgrade from 0.4.3 to 0.5 cause data template not found

### ISSUE THREAD

**Issue by Alvise88** [OpenNebula/terraform-provider-opennebula#284]
If in terraform code is present something similar to:

```
data "opennebula_template" "mytemplate" {
  name = "Rocky8"
}
```

upgrading to 0.5.0 throws this error message: no template match the tags

The function that trigger the issue is: https://github.com/OpenNebula/terraform-provider-opennebula/blob/dcca64db21443704e941cba928b5bbcb66aef1d8/opennebula/data_opennebula_template.go#L64

**Comment by treywelsh** [comment]
Thanks for reporting this.

This was introduced by PR #229 (issue #226), in which I reworked all datasources.
This is probably due a template that doesn't define some fields among `cpu`, `vcpu`, `memory` (the code supposed that they have to be defined).
I'll push a PR soon to fix this

**Comment by Alvise88** [comment]
Hi,

even with 0.5.1 i hit the same issue,: looking at the new code i really don't understand why, could it be the "name" case ?

I'am not able to define data for:

1. data "opennebula_virtual_network"
2. data "opennebula_template"

defining only the name attribute, the same works with 0.4.3

My OpenNebula version is 6.0.2

**Comment by treywelsh** [comment]
For virtual network I have a `Error: failed to get MTU attribute`
Is this the error you got ?

For the template datasource, could your provide the error message, and to help me to reproduce the problem providing the content of the  template you use (if possible) ?

**Comment by Alvise88** [comment]
> For virtual network I have a `Error: failed to get MTU attribute` Is this the error you got ?
> 
> For the template datasource, could your provide the error message, and to help me to reproduce the problem the content of the template you use (if possible) ?

No, in both cases i got `no virtual <type-name> match the constraints`. I'am sure both resources exists

**Comment by treywelsh** [comment]
For now I'm not able to reproduce an other problem that the virtual network error stated above.

It would be nice to have additional elements to reproduce (steps, template content, tfstate...), it may help

**Comment by Alvise88** [comment]
> For now I'm not able to reproduce an other problem that the virtual network error stated above.
> 
> It would be nice to have additional elements to reproduce (steps, template content, tfstate...), it may help

Cloning the template and becoming the owner permits to resolve the template; in other words if the template has different owner it is not resolved

**Comment by treywelsh** [comment]
It may be the same problem that mentioned in #252 for the template, in brief OpenNebula XML-RPC pool methods (have "visibility" parameters).
If it's the same problem, feel free to drop a comment in the issue.

I'll fix the virtual network problem I saw in an other PR.
