### ISSUE TITLE
[resource][VM] Update from 0.4.3 state resets disk in 0.5.0

### ISSUE THREAD

**Issue by danimo** [OpenNebula/terraform-provider-opennebula#294]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### Affected Resource(s)

- `opennebula_virtual_machine`

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.0"

  required_providers {
    opennebula = {
      source  = "opennebula/opennebula"
      version = "~> 0.4.3"
    }
  }
}

cat node.tf
resource "opennebula_virtual_machine" "reproducer" {
  name        = "reproducer.example.com"
  cpu         = 2
  vcpu        = 2
  memory      = 2048
  group       = oneadmin
  permissions = "760"

  context = {
    SSH_PUBLIC_KEY = var.init_ssh_keys
    NETWORK = "YES"
    SET_HOSTNAME = "$NAME"
    START_SCRIPT = ""
  }

  graphics {
    type   = "VNC"
    listen = "0.0.0.0"
    keymap = "de"
  }

  os {
    arch = "x86_64"
    boot = "disk0"
  }

  disk {
    image_id = 1
    size     = 30000
    driver   = "raw"
    target   = "vda"
  }

  nic {
    network_id = 1
  }
}
```

### Expected Behavior

When updating from 0.4.3 to 0.5.0, no change should be computed for the disk

### Actual Behavior

terraform computes the change `volatile_format = "raw" -> null` and subsequently swaps the disk, resulting in data loss, as the running machine will be stripped of the disk that its running on and receive a disk that it has no relation to:

```terraform
terraform plan -var-file="reproducer.tfvars" -var-file="credentials.tfvars" -state="reproducer.tfstate"
opennebula_virtual_machine.reproducer: Refreshing state... [id=589]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:
  # opennebula_virtual_machine.reproducer will be updated in-place
  ~ resource "opennebula_virtual_machine" "reproducer" {
        id            = "589"
        name          = "reproducer.example.com"
        # (18 unchanged attributes hidden)

      ~ disk {
          - volatile_format = "raw" -> null
            # (8 unchanged attributes hidden)
        }



        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
opennebula_virtual_machine.reproducer: Modifying... [id=589]
opennebula_virtual_machine.reproducer: Still modifying... [id=589, 10s elapsed]
opennebula_virtual_machine.reproducer: Still modifying... [id=589, 20s elapsed]
opennebula_virtual_machine.reproducer: Modifications complete after 21s [id=589]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Excerpt from TF state files.

**0_4_3.tfstate***:
```terraform
            "disk": [
              {
                "computed_driver": "raw",
                "computed_size": 30000,
                "computed_target": "vda",
                "computed_volatile_format": "raw",
                "disk_id": 0,
                "driver": "raw",
                "image_id": 6,
                "size": 30000,
                "target": "vda",
                "volatile_format": "",
                "volatile_type": ""
              }
```
**0_5_0.tfstate***:
```terraform
            "disk": [
              {
                "computed_driver": "raw",
                "computed_size": 30000,
                "computed_target": "vda",
                "computed_volatile_format": "raw",
                "disk_id": 0,
                "driver": "raw",
                "image_id": 6,
                "size": 30000,
                "target": "vda",
                "volatile_format": "",
                "volatile_type": ""
              }
            ],
```

### Steps to Reproduce

1. Setup the above terraform recipe with terraform
2. Update the dependency for the opennebula module to 0.5.0
3. `terraform apply -auto-approve -var-file="reproducer.tfvars" -var-file="credentials.tfvars" -state="reproducer.tfstate"`

### Extra Factoids

This used to also be a problem in 0.4.x, but the effect was inverse: the flag was added. This may be related to #239.

**Comment by johannwagner** [comment]
I tracked this down and I am pretty sure that this PR https://github.com/OpenNebula/terraform-provider-opennebula/pull/260 introduced the issue. I am currently working on a fix - hopefully without breaking the PR.

**Comment by johannwagner** [comment]
I provided a proposed fix for this problem.

**Comment by johannwagner** [comment]
I want to firmly describe the problem here:

In Terraform v0.4.3, `volatile_format` gets set in the terraform state by reading it from the OpenNebula cluster even it is not allowed to be set since `image_id` is declared. In v0.5.0 this behaviour changes and it only gets set to a value, if you specified a value in this field beforehand, e.g. setting it in `*.tf` files.

This results in a state change, no matter what. I cannot figure out a good way to fix this issue. 

There are two options:
1. We revert things back to the old behaviour.
2. We adapt the disk update method to only detach a disk, if there was a relevant update, which means, that you can have a state change without a detached disk.

**Comment by frousselet** [comment]
This issue is due to the 0.4.3 (where we had it at each plan/apply), the 0.5.0 fixes this.

The only workaround we have is editing the tfstate manually between the two versions during the migration. It's not perfect but it will work.
