### ISSUE TITLE
Bootable disk issue when using multiple disks

### ISSUE THREAD

**Issue by hbuttguavus** [OpenNebula/terraform-provider-opennebula#3]
I have an issue where the disk I want to use for booting the vm is not being used. Instead it is the second disk I have added.

How do i force or ensure that opennebula uses a specific disk to boot from when using the provider?

```
resource "opennebula_virtual_machine" "vm" {
  count = "${var.vm_count}"
  name = "${var.vm_name}-${format("%02d", count.index+1)}"
  permissions = "660"

  template_id = "${opennebula_template.vm_template.id}"

  cpu = "${var.cpu}"
  vcpu = "${var.cpu}"
  memory = "${var.memory}"

  os {
    arch = "x86_64"
    boot = "disk0"
  }

  disk {
    image_id = "${var.os_disk_imageid}"
    size = "${var.os_disk_size}"
    driver = "raw"
  }

  dynamic "disk" {
    for_each = var.extra_disks
    content {
      image_id = disk.value["image_id"]
      size = disk.value["size"]
      driver = "raw"
    }
  }

  nic {
    network_id = 0
  }
}
```

Seems like the second disk is being assigned the ID 0 even though it is declared after the disk I want to use to boot.

**Comment by jaypif** [comment]
Hi @hbuttguavus 

That's a very good question. 
May I suppose all you other disk have a type different from "OS" ? 

If it is the case, you can add the parameter `target` to your OS disk: `vda` (if you use virtio)

On our case, all VMs have at least:
- 1 OS disk with the OS image: `"target" = "vda"`
- 1 DATABLOCK disk of 1GB for the swap, `"target" = "vdb"`
And optionally, other datablock disks for other data usage.

I let `boot=""` in `os` configuration and the VM is correctly started.

Maybe you can try by adding this to you configuration ?

i need to check deeper exactly how to use the `boot` options too.

**Comment by hbuttguavus** [comment]
Hi @jaypif 
I am now using boot="" and have added targets for my disks as well but still see the same issue.

The disk I want to boot from is of type OS and any extra disks I add are of type DATABLOCK.

I can see in the terraform plan for one of my vms for example the following:

```
      + disk {
          + driver   = "raw"
          + image_id = 11
          + size     = 153600
          + target   = "vdb"
        }
      + disk {
          + driver   = "raw"
          + image_id = 11
          + size     = 153600
          + target   = "vdc"
        }
      + disk {
          + driver   = "raw"
          + image_id = 2
          + size     = 102400
          + target   = "vda"
        }
```
The disk with target vda shows up at the bottom. It is the disk I want to use to boot from.

**Comment by jaypif** [comment]
Hi,

I have maybe a clue. I use TypeSet for the list of disks (or nic) but I should use TypeList to force ordering.

In your case the OS disk is maybe not the disk with id 0 which can explain your issue.

I will push a fix to be sure the order is the one from the configuration. In you case you expect the disk with id 0 to be the first one.

**Comment by jaypif** [comment]
Hi @hbuttguavus 

the PR #9 might unlock you for this.
I will add you as reviewer (if you think you can give an advice so as another people too don't worry).

regards

**Comment by jaypif** [comment]
Hi @hbuttguavus the PR #9 has been merged. 

to test if you still have the issue, are you able to get the code and compile the provider to test if this fix solves your issue ?

Thanks

**Comment by hbuttguavus** [comment]
I am no longer facing this issue. Thanks!

**Comment by jaypif** [comment]
Great :)
