### ISSUE TITLE
[v0.5.1] Regression with multi-line context entries

### ISSUE THREAD

**Issue by danimo** [OpenNebula/terraform-provider-opennebula#309]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### Affected Resource(s)

- opennebula_virtual_machine

### Expected Behavior

A resource with the definition:

```terraform
....
  context = {
    SSH_PUBLIC_KEY = <<-EOF
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAdpks3NLPqv3hrZAZ5wJwXlgGcTbmG+BCG4fxxw5 foo
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINwq3MeJKlP9biT4XyqSkAzeq3Ri3kmincCMefxfJz bar
EOF
  }
```
creates a context variable like so:

```
....
SSH_PUBLIC_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAdpks3NLPqv3hrZAZ5wJwXlgGcTbmG+BCG4fxxw5 foo
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINwq3MeJKlP9biT4XyqSkAzeq3Ri3kmincCMefxfJz bar"
....
```
leading to a `.ssh/authorized_keys` file that contains one key per line.

### Actual Behavior

creates a context variable like so:

```
....
SSH_PUBLIC_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPAdpks3NLPqv3hrZAZ5wJwXlgGcTbmG+BCG4fxxw5 foo\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINwq3MeJKlP9biT4XyqSkAzeq3Ri3kmincCMefxfJz bar"
....
```
leading to a `.ssh/authorized_keys` file that has all keys concatenated in a single line.

### Steps to Reproduce

1. Upgrade from version 0.5.0 to 0.5.1

2. `terraform apply` (might need changes to the keys)

### References

It is reasonable to assume that the Switch to SDKv2 (https://github.com/OpenNebula/terraform-provider-opennebula/pull/161) has introduced this regression, though we haven't done any bisecting yet.

**Comment by treywelsh** [comment]
This is due to PR #270, in which we updated the goca dependency to retrieve 6.4 OpenNebula changes.

Among other changes, the OpenNebula issue that modified the goca behavior regarding character escaping is https://github.com/OpenNebula/one/issues/5785


The change is in `String()` dynamic template method which escape now much more characters

**Comment by treywelsh** [comment]
Issue opened to the one repository: https://github.com/OpenNebula/one/issues/5914
