### ISSUE TITLE
"resource not found" when creating any resource

### ISSUE THREAD

**Issue by mateusmuller** [OpenNebula/terraform-provider-opennebula#31]
Hi guys,
I have tested with both Terraform 11 and 12.
I have tested with network and image resources and the same happens.
I am using MacOS Mojave 10.14.6.
Actually it creates the resource, but it shows an error message in the end, which is strange.

```
opennebula_virtual_network.vnet: Destroying... [id=17]
opennebula_virtual_network.vnet: Destruction complete after 1s
opennebula_virtual_network.vnet: Creating...

Error: resource not found

  on main.tf line 7, in resource "opennebula_virtual_network" "vnet":
   7: resource "opennebula_virtual_network" "vnet" {
```

This is the code:

```
provider "opennebula" { 
    endpoint = "${var.one_endpoint}"
    username = "${var.one_username}"
    password = "${var.one_password}"
}

resource "opennebula_virtual_network" "vnet" {
    name = "4F_bridge_network"
    permissions = "660"
    group = "terraform"
    bridge = "br0"
    physical_device = "enp8s0"
    type = "bridge"
    mtu = 1500
    ar {
        ar_type = "IP4"
        size = 16
        ip4 = "192.168.0.30"
    }
    dns = "192.168.0.1"
    gateway = "192.168.0.1"
    security_groups = [ 0 ]
}
```

It creates the resource, but because of the error, I cannot send the output to another module.
I could not find anything related to this.
May you help here?

**Comment by jaypif** [comment]
hi @mateusmuller 

Sorry for the late reply

What is the version of OpenNebula you use ?
What is the release of the provider ?

If the resource is well created on One it means the error occurs when Terraform performs the "Read" part before displaying the output.

thank you for your answers

**Comment by puppetmaster** [comment]
Hi @jaypif 
  I have the same issue with : 
-  OpenNebula 5.8.5
- terraform-provider-opennebula v0.1.1

This occurs only with virtual_networks and only if I try to create virtual_machines.

Maybe this can help : 
[log.txt](https://github.com/terraform-providers/terraform-provider-opennebula/files/4516730/log.txt)

**Comment by puppetmaster** [comment]
Ok ! Welcome to the 4th dimension !

So I decided to track this so called "bug", I put on my gopher slippers and game on !
- [x] Fork main project 
- [x] Track down the "Read" lead proposed by @jaypif 
- [x] Add some more debug in the suspect function 
```diff --git a/opennebula/resource_opennebula_virtual_network.go b/opennebula/resource_opennebula_virtual_network.go
index a7ceb8ad..4c87b235 100644
--- a/opennebula/resource_opennebula_virtual_network.go
+++ b/opennebula/resource_opennebula_virtual_network.go
@@ -667,8 +667,10 @@ func resourceOpennebulaVirtualNetworkRead(d *schema.ResourceData, meta interface
                                        return nil
                                }
                        }
+                       log.Printf("[DEBUG] CADOLES 1 [%s]", err)
                        return err
                default:
+                       log.Printf("[DEBUG] CADOLES 2 [%s]", err)
                        return err
                }
        }
@@ -700,6 +702,7 @@ func resourceOpennebulaVirtualNetworkRead(d *schema.ResourceData, meta interface
 
        err = flattenVnetTemplate(d, &vn.Template)
        if err != nil {
+               log.Printf("[DEBUG] CADOLES 3 [%s]", err)
                return err
        }
 ```
- [x] Build my new dummy version of the provider !
- [x] Put it in place !
- [x] terraform init 
- [x] TF_LOG_PATH=./out.log TF_LOG=DEBUG terraform apply -var-file=main.tfvars 

And witness the magic ... no more so called bug ... 
`Apply complete! Resources: 33 added, 0 changed, 0 destroyed.`

WTF ???

If I remove this lines the magic don't work anymore and back to the good old bug.

**Comment by puppetmaster** [comment]
Wait for it, it gets even weirder ..
```
diff --git a/opennebula/resource_opennebula_virtual_network.go b/opennebula/resource_opennebula_virtual_network.go
index a7ceb8ad..b7c99423 100644
--- a/opennebula/resource_opennebula_virtual_network.go
+++ b/opennebula/resource_opennebula_virtual_network.go
@@ -700,6 +700,7 @@ func resourceOpennebulaVirtualNetworkRead(d *schema.ResourceData, meta interface
 
        err = flattenVnetTemplate(d, &vn.Template)
        if err != nil {
+               log.Printf("[DEBUG] CADOLES 3 [%s]", err)
                return err
        }
 ```
This line : log.Printf("[DEBUG] CADOLES 3 [%s]", err) makes the "bug" go away ... 

Maybe somebody with more knowledge about this provider code than me can make sens of this.

**Comment by jaypif** [comment]
Hi @puppetmaster 

Sorry for the late reply

It looks like there is a race condition between Terraform and OpenNebula.
Terraform, developed in GO will send parallel requests to the OpenNebula server.
But I think in your case the network is not ready (creation is not finished) while the VM needs it.

Can you try to add `depends_on` (https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies) in the VM resource ?
I think that way you will explicitly inform Terraform to wait for Network to be ready before using it in the VM

Hope this helps

Regards

**Comment by wolfff** [comment]
This bug hit me again, today. Running still 0.3.0 of the opennebula provider with Terraform v1.1.4 against opennebula 6.2.0-1.ce.  Creating resources fail according to tf, but like the original report, the resource is created in one and on further plan applies treated as 'tained'. Setting depends_on for the vm requiring the virtual network resource does not solve it. 

So any news on this ?

**Comment by wolfff** [comment]
Actually, when following the idea to insert debug statements in the code of the provider, I finally detected that the issue was caused in the function changeVmGroup as I have passed a `group =` arg to the opennebula_virtual_machine resource definition which does not exist. After removing that group attribute, creation of the farm succeeded. 
So I guess error handling should be improved, so that already during the `terraform plan` step missing resources (read: non existing group in OpenNebula) is detected and an appropriate error message is given.

**Comment by jaypif** [comment]
Hi @wolfff 

Oh that's really good to know and I am really sorry about this issue you are facing about.

The group attribute is here to precise the group which should own the VM. If it is not specified it keeps the terraform user's primary group.

Usually if the group does not exist an error is raised. 

We will take a look about improving the error handling here.

Thanks

**Comment by jaypif** [comment]
Hi @wolfff 

I opened #199  to follow the error handling issue.
It might help you about the issue you faced here but I am not sure it answer the original issue opened by @mateusmuller and investigated by @puppetmaster
