### ISSUE TITLE
Allow support for marking a specific Context Variable as absent (not creating it)

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/terraform-provider-opennebula#311]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm using a unique `opennebula_virtual_machine` template with multiple setups/situations, and one of the scenario/situations need a variable, let's call it `NOT_ALWAYS_DEFINED`, to be defined to `some_value`.

I want to use this same template with some other setups/situations that don't need this variable, and cannot have an empty value either, meaning that I need this variable to simply be absent from the specific VM.

Because of that, I'm curious to know if there would be a way to tell the OpenNebula Provider to totally ignore the variable `NOT_ALWAYS_DEFINED` from the Context Variables.

Is there any special tag/content/logic/magic that I could use to fully remove this variable when it's empty or set to a specific value ?

### New or Affected Resource(s)

- opennebula_virtual_machine

### Potential Terraform Configuration

```hcl
resource "opennebula_virtual_machine" "example" {

<...>

  context = {
    HOSTNAME     = "$NAME"
    ALWAYS_DEFINED = var.always_defined    # Always defined
    NOT_ALWAYS_DEFINED = var.some_value    # Not always defined
  }
  
<...>
}
```

### Suggestion / Idea

I'm thinking of something like that, but no idea how it could be implemented.

```hcl
    NOT_ALWAYS_DEFINED = var.some_test == "yes" ? var.some_value : Null
    NOT_ALWAYS_DEFINED = var.some_test == "yes" ? var.some_value : <absent>
```

Thanks !

Thomas

**Comment by frousselet** [comment]
Hi Thomas,

I'm not sure the provider should manage this, but maybe OpenNebula yes.

In the meantime, what you can do is transform your context before using it. I tried something like this (it's not perfect at all):

```hcl
# Variable containing the context
variable "ctx" {
  default = [
    {
      key   = "ALWAYS_DEFINED",
      value = "foo"
    },
    {
      key   = "NOT_ALWAYS_DEFINED",
      value = ""
    }
  ]
}

# Remove empty values
locals {
  ctx_no_empty = {
    for ctx in var.ctx : ctx.key => ctx.value if ctx.value != ""
  }
}

resource "opennebula_virtual_machine" "example" {
  # ...

  context = local.ctx_no_empty

  # ...
}

output "new_ctx" {
  value = local.ctx_no_empty
}
```

```shell
$ terraform plan

Changes to Outputs:
  + new_ctx = {
      + ALWAYS_DEFINED = "foo"
    }

...
```

François

**Comment by Th0masL** [comment]
Hey François !

Thanks a lot for your suggestion !

The workaround you suggested can totally work for me, so I'll take that as a valid solution to my problem.

I also believe that you are right in saying that it would probably make more sense for this kind of logic to be included in Terraform itself and not in this provider.

I'll open a suggestion on the Terraform GitHub repo.

Thank you and have a good day.

Thomas
