### ISSUE TITLE
introduce `opennebula_disk`

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#318]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the virtual machine resource, disks are managed through a list.
This is rather complex to manage, this lead me to introduce some `computed_*` attributes, and as far as I remember this doesn't really help terraform with the depencies (trying to detach a disk and delete the related image in the same apply make OpenNebula fail when it try to delete the image first).

Moving disk management code outside of the VM would simplify the code, and the code moved to the `opennebula_disk` would also be simpler.

I proposed the name `opennebula_disk` because it's shared between `opennebula_virtual_machine` and `opennebula_virtual_router_instance`. 

There is other resources in which it's possible to describe disks: `opennebula_template` and `opennebula_virtual_router_instance_template`.

To keep the capacilities to create virtual machine with disk attached, the disk sections could be keep. Later only the virtual machine disk update code could be deprecated and then removed.

Infortunately with the lifecycle in the virtual machine resource the `on_disk_change` attribute don't work anymore.
I don't have any solution for a replacement: it's not possible to only use the `lifecycle` attribute `replace_triggered_by` in the VM to recreate the VM as it introduce a cycle between the VM and the disk (depends on the VM via `vm_id`) in terraform dependency graph.
I tried to find a solution in adding an attribute on disk resource side to restart the VM via powerOff/resume or reboot actions but this is rather complex (a lot of VM state management across CRUD operations... etc.).
`on_disk_change` will be deprecated for now.

### New or Affected Resource(s)

- opennebula_virtual_machine
- opennebula_virtual_router_instance
- opennebula_disk

### Potential Terraform Configuration

```hcl
resource "opennebula_template" "testtemplate" {
  name        = "template"
  cpu         = 1
  memory      = 1024
  group       = "terraform"
  permissions = "660"

  # bunch of sections ...

  # disk attached at VM creation
  disk {
    image_id = opennebula_image.example.id
    target   = "vda"
  }

}

resource "opennebula_virtual_machine" "testvm" {
  name        = "test-virtual_machine"
  group       = "oneadmin"
  permissions = "660"

  template_id = opennebula_template.testtemplate.id

  # bunch of sections ...

  # we won't be able to update this disk later
  disk {
    image_id = 2
    target   = "vdb"
  }

  hard_shutdown = true

  lifecycle {
    ignore_changes = [
      disk,
    ]
  }
}

# hotplugged disks
resource "opennebula_disk" "data_disk" {
    vm_id          = opennebula_virtual_machine.testvm.id
    volatile_type  = "fs"
    format         = "raw"
    size           = 16
    target         = "vdc"
    final_snapshot = true # Create a snapshot when the disk is destroyed
}

resource "opennebula_disk" "os_disk" {
    vm_id    = opennebula_virtual_machine.testvm.id
    image_id = 2
    target   = "vdd"
}
```

### References

- #59 is the first PR that tried to introduce disk update
- #80 is the PR that add NIC update and also modify disk update, `computed_*` attributes where introduced here. Read the issue comments
- #281 
- #291 

There is some other minor PRs to add attributes and fixes to the virtual disk management

**Comment by frousselet** [comment]
As seen, the user should manually manage the VM state after a disk change.
This can be managed by Terraform by using a `null_resource` with an RPC API call.

Deprecate #156 `on_disk_change`.

**Example:**

_main.tf_

```hcl
resource "opennebula_virtual_machine" "testvm" {
  # ...
}

resource "opennebula_disk" "data_disk" {
  vm_id          = opennebula_virtual_machine.testvm.id
  volatile_type  = "fs"
  format         = "raw"
  size           = 16
  target         = "vdc"
  final_snapshot = true # Create a snapshot when the disk is destroyed
}

resource "null_resource" "restart_vm" {
  depends_on = [
    opennebula_disk.data_disk
  ]

  triggers = {
    disk_id             = opennebula_disk.data_disk.id
    disk_size           = opennebula_disk.data_disk.size
    disk_format         = opennebula_disk.data_disk.format
    disk_target         = opennebula_disk.data_disk.target
    disk_ volatile_type = opennebula_disk.data_disk.volatile_type
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "python3 ${path.module}/scripts/restart_vm.py"
    environment = {
      VM_ID = opennebula_virtual_machine.testvm.id
    }
  }
}
```

_scripts/restart_vm.py_

```python
import pyone
import ssl
import os

one = pyone.OneServer(os.environ['TF_VAR_endpoint'], session="{}:{}".format(
    os.environ['TF_VAR_username'], os.environ['TF_VAR_password']), context=ssl._create_unverified_context())

one.vm.action("reboot", os.environ['VM_ID'])
```
