### ISSUE TITLE
vRouter integration

### ISSUE THREAD

**Issue by turb0steve** [OpenNebula/terraform-provider-opennebula#32]
**I can't thank you all enough for your hard work on this provider - it's truly invaluable.**
I fully appreciate the decision to focus on VMs and networking, as client workloads generate far more operational effort than managing the cluster itself.   

**Are there any plans to add vRouter support?**   
At the moment I am having to build vRouters using null-resource and firing onevrouter commands, which seems more than a little primitive given the elegance of using a TF provider.

**Is there a 'features roadmap' anywhere?**
I see some mention of a roadmap/timeline in https://github.com/terraform-providers/terraform-provider-opennebula/issues/4   so I assume the work has been on the features, not the future? :smiley:

Thank you again, team - this provider really adds so much value to OpenNebula.

**Comment by jaypif** [comment]
hi @SteveBristow 

Thank you very much for your message. It is always a pleasure to read this when someone open an issue :D.

About vRouter, I tried at the beginning of the development of this provider and I faced some issues. But I think we can add it in the Roadmap as some improvement were performed on Goca (OpenNebula GOlang bindings) and it can help a lot.

As I am writing "Roadmap", actually there is not a formal Roadmap because it is quite new yet and for the moment we are not enough to maintain this correctly. I hope, by the end of the year we will have something :).
The plan is to release a v0.2 quite soon and to add new stuffs for a 0.3. 
Vrouter can be part of the 0.3 release.

Thank you

**Comment by turb0steve** [comment]
Thanks @jaypif  (et merci), 
vRouter can feel a little bit "added on" to OpenNebula - I think it's still finding it's way into the core - but it is a deeply useful, as NFV is a key component of any private cloud - certainly the SDN is one of the key drivers for our adoption.   

I will try and contain my excitement for 0.3, and keep null_resourcing bash scripts in the meantime.

I hope your good work gets the recognition (and support) it deserves - this project seems critical to the continued existence of OpenNebula given the widespread adoption of Terraform.

Thank you once again!

**Comment by jaypif** [comment]
Hi @SteveBristow 

I am thinking about this issue.
Vrouter in OpenNebula is an appliance on top of VMs.
To deploy a Vrouter you need to create a Vrouter template (which is a teamplate with the attribute `VROUTER = YES`) and then you can create a Vrouter. Finally you need to instanciate Vrouter using the Vrouter ID and the template ID.
After instanciation you have one or several VMs "Vrouter" running.

My questions is how you want to manage Vrouter and VMs running under Vrouter ?

Usually when a resource is created with terraform, the provider call "allocate" function. So in our case it will create a vrouter appliance.
But it won't instanciate Vrouter VMs. Is it what you expect ? Or do you also want to instantiates VRouter VMs when Vrouter are created ?

IMHO, It is better to add a vrouterid parameter in `opennebula_virtual_machine` resource with will instanciate a vrouter VM.
The resource Virtual router is here only to manage the "appliance" part. Does is seems correct for you ?

Actually the idea is to have the same logic with Virtual router than the one already implemented for VM Groups.

This logic means you need to delete all VMs before deleting a Virtual router in case of deletion
