### ISSUE TITLE
introduce `opennebula_nic`

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#320]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This issue has similar arguments that #318 

### New or Affected Resource(s)

- opennebula_virtual_machine
- opennebula_virtual_router_instance
- opennebula_nic

### Potential Terraform Configuration

```hcl
resource "opennebula_template" "testtemplate" {
  name        = "template"
  cpu           = 1
  memory    = 1024
  group       = "terraform"
  permissions = "660"

  # bunch of sections ...

  # we won't be able to update this nic later from the VM description
  nic {
    network_id   = 2
    ip                  = "172.16.100.131"
  }

}

resource "opennebula_virtual_machine" "testvm" {
  name        = "test-virtual_machine"
  group       = "oneadmin"
  permissions = "660"

  template_id = opennebula_template.testtemplate.id

  # bunch of sections ...

  # we won't be able to update this nic later
  nic {
    network_id   = 2
    ip                  = "172.16.100.132"
  }

  hard_shutdown = true

  lifecycle {
    ignore_changes = [
      nic,
    ]
  }
}

resource "opennebula_nic" "testnic" {
    vm_id           = opennebula_virtual_machine.testvm.id
    network_id   = 2
    ip                  = "172.16.100.133"
}
```

### References

- similar to #318 
- #35 
- #281

**Comment by frousselet** [comment]
What do you mean by `# we won't be able to update this nic later`? (Same question for #318)

**Comment by treywelsh** [comment]
I mean it's possible to create this VM with a list of NICs **attached at creation**, but we won't be able to update them later (i.e. change NIC attribute values, to remove them...). 
I mean we won't be able to update unless we try some more complex manipulations like import the disk resource, or even modify the state directly.
Same idea for the disk, we want to keep the capability to create a VM with a disk attached at creation (OS disk for instance).
Then the VM is created, then boot and runs in one step.

If we completely remove the disk/nic from the VM resource schemas, it appears to me that we could only create the VM without nic/disk attached at creation. Then attach a disk/nic would require a second step. Then, should the VM be restarted to boot on the attached disk ?

I'm trying to find the more convenient behavior

By the way, I update the example code, I missed to add some lifecycle to avoid conflicts between the opennebula_virtual_machine and the opennebula_disk/nic code
