### ISSUE TITLE
Get VM template by regexp and most_recent

### ISSUE THREAD

**Issue by ghost** [OpenNebula/terraform-provider-opennebula#322]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's will be good idea:
- to get `data "opennebula_template"` by regexp 
- add option `most_recent` - if more than one result is returned, use the most recent
It may be done like in AWS, for example https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

### New or Affected Resource(s)

- opennebula_template

### Potential Terraform Configuration

```hcl
data "opennebula_template" "example" {
  most_recent      = true
  name_regex       = "^myopennebula-\\d{3}"
}
```

**Comment by frousselet** [comment]
Thanks for the suggestion.

In the AWS AMI case, the `most_recent` attribute is useful since an AMI is versioned, which is not the case with an OpenNebula template.

So with this regex attribute you will get an array of templates. Maybe we can add an attribute to choose what key is used to order the array?

But anyway, if the `data` can return more than one attribute (which is a use case of a regex search), it should be `opennebula_templates` (with an 's') along side `opennebula_template`, because `opennebula_template` should return zero or one template and not zero or N.

**Comment by ghost** [comment]
Hi @frousselet! 
Thanks for reply. Yes, I mean that searcing by regex can return more than one `opennebula_template` - in our case `opennebula_templates`.
And, I think, that `most_recent` can be ordered by `Registration time`, i.e. last uploaded template

**Comment by frousselet** [comment]
Hello,

So we can think about something like this:

```hcl
data "opennebula_templates" "example" {
  name_regex = "^myopennebula-\\d{3}"

  order_by = [
    "register_time",
    "<second_level_order>",
    # ...
  ]
  order_direction = "DESC"
}
```

Then you can select the first result of the array.

@treywelsh, what do you think?

**Comment by Prakharkarsh1** [comment]
Hii @ghost i want to contribute to fix this issue

**Comment by deynekoaa** [comment]
Hi @Prakharkarsh1!
It will be great, if you can fix this issue

**Comment by frousselet** [comment]
Hello @Prakharkarsh1,

Sorry for the late reply.
It would be great if you can contribute.

This issue probably apply to other data sources.

**Comment by treywelsh** [comment]
by `most_recent`, we means the most recent creation date (regardless of the template updates), right ?
It seems that the `Register time` field of the template in OpenNebula could be used to compare creation date.

Else I'm ok with @frousselet proposal, but do we need to order based on **several** fields ?
In addition, the datasource you propose seems closer to [aws_ami_ids](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami_ids) than the initially mentionned resource [aws_ami](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami) which seems to pick the first AMI of the list

**Comment by treywelsh** [comment]
I made a minimal draft implementation that works in a similar way that @frousselet proposed (it's a quickly written stuff so it's easy to make it crash, be careful) in #388.
The goal of this draft is only to show a way to do, I'm open to fully rewrite it if it's not useful.

This allows something like:
```
data "opennebula_templates" "test" {
  name_regex = "^myopennebula-\\d{3}"
  has_cpu    = true
  order_by   = "register_date"
  order      = "DESC"
}

resource "opennebula_virtual_machine" "example2" {
  name        = "test2"
  description = "VM"

  memory      = 64
  cpu         = 0.1

  template_id = data.opennebula_templates.test.templates[2].id
}
```
The implementation store a list of templates data (don't know if all of these data are useful but I had in mind that this could be used to chose a template based on it's datas when automating stuffs).

Feel free to test it and give feedback it's helpful
