### ISSUE TITLE
Skip TLS verification for self-signed certs

### ISSUE THREAD

**Issue by bsanders** [OpenNebula/terraform-provider-opennebula#328]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On a dev cluster I was recently working with, the terraform provider failed to connect due to the api server using a self-signed cert.  While this is not something that should run in production, it would be useful to still have the ability to talk to dev/test clusters this way.  I was able to patch the provider to enable progress, and I'm wondering if upstream is interested in this change?

### New or Affected Resource(s)

No resources affected, but the provider itself.

### Potential Terraform Configuration

N/A

### References

None that I could find.

**Comment by bsanders** [comment]
The diff is small, but obviously this just hardcodes to always skip TLS verification, which is 100% not good.  If the project is interested in this feature, I would need to know where you want to enable/disable it.  Off the top of my head, you'd want an environment variable.  Maybe a config option in the provider section of the .tf file?

```
diff --git a/opennebula/provider.go b/opennebula/provider.go
index 7e45d581..3b4ff3af 100644
--- a/opennebula/provider.go
+++ b/opennebula/provider.go
@@ -3,6 +3,8 @@ package opennebula
 import (
        "context"
        "log"
+       "net/http"
+       "crypto/tls"
 
        ver "github.com/hashicorp/go-version"
        "github.com/hashicorp/terraform-plugin-sdk/v2/diag"
@@ -112,10 +114,16 @@ func providerConfigure(ctx context.Context, d *schema.ResourceData) (interface{}
                })
                return nil, diags
        }
-
-       oneClient := goca.NewDefaultClient(goca.NewConfig(username.(string),
+       // goca allows for passing in a custom http.client if using NewClient instead of NewDefaultClient,
+       // which allows us to conditionaly disable TLS verification for self-signed certs
+       tr := &http.Transport{
+               TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
+       }
+       insecureClient := &http.Client{Transport: tr}
+       oneClient := goca.NewClient(goca.NewConfig(username.(string),
                password.(string),
-               endpoint.(string)))
+               endpoint.(string)), insecureClient)
 
        versionStr, err := goca.NewController(oneClient).SystemVersion()
        if err != nil {
```

**Comment by frousselet** [comment]
Hi Bill,

Thanks for pointing this out.

So I guess we can consider something like below?

```hcl
provider "opennebula" {
  endpoint      = "<ENDPOINT URL>"
  flow_endpoint = "<FLOW ENDPOINT URL>"
  username      = "<USERNAME>"
  password      = "<PASSWORD OR TOKEN>"
  insecure      = true # default is false
}
```

I add this to the 1.0.0 milestone.

**Comment by bsanders** [comment]
Yeah, that was sort of what I was imagining as well.  If that looks good to you, I'll look into it.
