### ISSUE TITLE
SCHED_REQUIREMENTS and SCHED_DS_REQUIREMENTS are set to null after the VM has been deployed

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/terraform-provider-opennebula#330]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
root@ubuntu2004-minione-6-4-5WBtH-0:~# terraform --version
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/opennebula/opennebula v0.5.2
```

### Affected Resource(s)

- opennebula_virtual_machine

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    opennebula = {
      source  = "opennebula/opennebula"
      version = "~> 0.5.2"
    }
  }
}

provider "opennebula" {
 endpoint = "http://localhost:2633/RPC2"
 username = "oneadmin"
 password = "N7i40tEkAn"
 #username = "test"
 #password = "test"
}

resource "opennebula_virtual_machine" "bug_report2" {
  template_id = 0


  name        = "virtual-machine-terraform"
  description = "VM"
  cpu         = 1
  vcpu        = 1
  memory      = 128
  group       = "oneadmin"
#  sched_requirements = "FREE_CPU > 60"

}
```

### Expected Behavior

Issuing a `terraform apply` after a VM has been deployed by the terraform provider shouldn't override the SCHED_REQUIREMENTS. This happens when the SCHED_REQUIREMENTS is obtained via `template_id` and not directly stated on the VM tf definition. The same applies for SCHED_DS_REQUIREMENTS.

### Actual Behavior

On re-applying the configuration, the new Virtual Machine gets its SCHED_REQUIREMENTS set to null

```
root@ubuntu2004-minione-6-4-5WBtH-0:~#  onevm show 7 | grep -i sched_requirements
SCHED_REQUIREMENTS="FREE_CPU > 60"
root@ubuntu2004-minione-6-4-5WBtH-0:~# terraform apply
opennebula_virtual_machine.bug_report2: Refreshing state... [id=7]
data.opennebula_template.alpine: Reading...
data.opennebula_template.alpine: Read complete after 0s [id=0]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # opennebula_virtual_machine.bug_report2 will be updated in-place
  ~ resource "opennebula_virtual_machine" "bug_report2" {
        id                 = "7"
        name               = "virtual-machine-terraform"
      - sched_requirements = "FREE_CPU > 60" -> null
        tags               = {}
        # (20 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opennebula_virtual_machine.bug_report2: Modifying... [id=7]
opennebula_virtual_machine.bug_report2: Modifications complete after 5s [id=7]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

alpine_template = {
  "context" = tomap(null) /* of string */
  "cpu" = 1
  "disk" = tolist([
    {
      "driver" = ""
      "image_id" = 0
      "size" = 0
      "target" = ""
      "volatile_format" = ""
      "volatile_type" = ""
    },
  ])
  "graphics" = tolist(null) /* of object */
  "id" = "0"
  "memory" = 128
  "name" = "Alpine Linux 3.14"
  "nic" = tolist([
    {
      "ip" = ""
      "mac" = ""
      "model" = ""
      "network" = "vnet"
      "network_id" = -1
      "physical_device" = ""
      "security_groups" = tolist([
        0,
      ])
      "virtio_queues" = ""
    },
  ])
  "os" = tolist(null) /* of object */
  "tags" = tomap({
    "CPU" = "1"
    "LOGO" = "images/logos/linux.png"
    "LXD_SECURITY_PRIVILEGED" = "true"
    "MEMORY" = "128"
    "SCHED_REQUIREMENTS" = "FREE_CPU > 60"
  })
  "vcpu" = tonumber(null)
  "vmgroup" = tolist(null) /* of object */
}
root@ubuntu2004-minione-6-4-5WBtH-0:~# onevm show 7 | grep -i sched_requirements
```

### Steps to Reproduce

1. Create a VM resource definition. Said definition won't contain a `sched_requirements` declaration.
2. Set a `template_id` argument that references a VM Template containing SCHED_REQUIREMENTS
3. `terraform apply`
4. `terraform apply`

### References

- #0000

**Comment by treywelsh** [comment]
We could do something similar to the existing `template_disk` and `template_disk` sections, i.e. keep a kind of `template` section inside of the `virtual_machine` resource that don't conflict with the VM attributes.

By default, the attributes of the `template` section would be used. But If the user override some attributes in the virtual_machine  descriptions these last ones would be used.
The instantiated VM couldn't be used to modify the template content.

Would it be satisfying ?

**Comment by OpenNebulaSupport** [comment]
Does this mean that 
- on the first `terraform apply`, the SCHED_REQUIREMENTS and SCHED_DS_REQUIREMENT gathered from the template referenced by `template_id` would be exported as attributes
- on the 2nd `terraform apply` those attributes would not change because they were previously exported whereas before, they weren't ?

**Comment by treywelsh** [comment]
I'm not sure I was clear so just to be sure we understand the same thing, some more details:

There is a diff because the `SCHED_REQUIREMENTS` is defined in the template but is not defined in the virtual machine resource (in the TF file).
The inheritance of `SCHED_REQUIREMENTS` is done on cloud side at VM instantiation and the provider is not aware of that.
Then terraform reads the datas on cloud side, and see that there is a `SCHED_REQUIREMENTS` in the VM on cloud side but not in it's TF description.
So terraform see a diff and believe that this value should be removed on cloud side.

It's why I propose this way to do to avoid the diff seen by terraform, i.e. keeping some template datas inside the VM description (via a new VM schema section that the user couldn't modify but that would be visible in the tfstate).
Then we could have VM operation (CRUD) that would act conditionally based on this section.
Let's take an example with only the `tags` section, let's call our new section `template_tags`.

In our case, a template with a `template_id` defined, the provider VM read method could do some more complex operations like:
If `SCHED_REQUIREMENTS` is defined in the `template_tags` section of the VM, but not defined in the `tags` section, don't read `SCHED_REQUIREMENTS` from the VM cloud description.
If `SCHED_REQUIREMENTS` is defined in the `template_tags` section of the VM, and also defined in the `tags` section, only work with the `tags` value

Is that more clear ? Feel free to drop a comment on this proposal

**Comment by OpenNebulaSupport** [comment]
So the named `template_tags` section would be used to flag which attributes bypass the diff, unlike manually setting said attribute with a prefixed value on the resource definition, for example `sched_requirements = "FREE_CPU > 60"`. Is this correct ?

**Comment by treywelsh** [comment]
yes, this would allow to bypass the diff in the case of this issue.
It's not perfect but I don't know any tool in the terraform SDK to manage inter resources relationships inside the provider to handle this.

An other way to remove the diff would be to copy manually the attribute from the template tf description to the VM description but I'm not satisfied with this solution

**Comment by OpenNebulaSupport** [comment]
Okay, seems reasonable. Thanks a lot for the detailed explanation.
