### ISSUE TITLE
Template GetPair: key GROUP_DN not found

### ISSUE THREAD

**Issue by DoomProger** [OpenNebula/terraform-provider-opennebula#355]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.3.1  
on windows_amd64  
provider registry.terraform.io/opennebula/opennebula v1.0.1  

### Affected Resource(s)

- opennebula_6.4.0

### Terraform Configuration Files

```hcl
resource "opennebula_group" "one62_admins" {
  name = "test1"
  delete_on_destruction = false
  tags = {
    GROUP_DN="cn=one62_admins,cn=groups,cn=accounts,dc=local,dc=cloud"
  }
  sunstone {
    default_view = "user"
    views = "groupadmin,cloud,user"
    group_admin_default_view = "admin"
    group_admin_views = "groupadmin,cloud,user,admin"
  }
}

```

### Debug Output
First terraform apply is correct, but when try in second time it show that some settings will be remove and an error is returned about key.
```
Terraform will perform the following actions:

  # opennebula_group.one62_admins will be updated in-place
  ~ resource "opennebula_group" "one62_admins" {
        id                    = "173"
        name                  = "test1"
        tags                  = {
            "GROUP_DN" = "cn=one62_admins,cn=groups,cn=accounts,dc=local,dc=cloud"
        }
      - template              = <<-EOT
            GROUP_DN="cn=one62_admins,cn=groups,cn=accounts,dc=local,dc=cloud"
            SUNSTONE=[
                DEFAULT_VIEW="user",
                GROUP_ADMIN_DEFAULT_VIEW="admin",
                GROUP_ADMIN_VIEWS="groupadmin,cloud,user,admin",
                VIEWS="groupadmin,cloud,user" ]
        EOT -> null
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Error
```
╷
│ Warning: Argument is deprecated
│
│   with opennebula_group.one62_admins,
│   on terraform.tf line 40, in resource "opennebula_group" "one62_admins":
│   40:   delete_on_destruction = false
│
│ use Terraform lifcycle Meta-Argument instead.
│
│ (and 2 more similar warnings elsewhere)
╵
╷
│ Error: Failed to flatten template
│
│   with opennebula_group.one62_admins,
│   on terraform.tf line 38, in resource "opennebula_group" "one62_admins":
│   38: resource "opennebula_group" "one62_admins" {
│
│ group (ID: 173): Template GetPair: key GROUP_DN not found
```

### Expected Behavior
There are no changes to group, because it got created 3 minutes before, so I would expect the provider to show that all the resources are already up-to-date.

### Actual Behavior
It detects non-existing changes and deletes them. The group becomes unconfigured.

### Steps to Reproduce

Fist time group create sussesful  
In second time, some attributes are remove  
1. `terraform apply`
2. `terraform apply`

### References

- #0000

**Comment by frousselet** [comment]
Hello,

`template` is deprecated and you may have to use the [`ignore_change`](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) lifecycle to prevent conflicts with the `sunstone` attribute.

```hcl
resource "opennebula_group" "one62_admins" {
  name = "test1"
  delete_on_destruction = false
  tags = {
    GROUP_DN="cn=one62_admins,cn=groups,cn=accounts,dc=local,dc=cloud"
  }
  sunstone {
    default_view = "user"
    views = "groupadmin,cloud,user"
    group_admin_default_view = "admin"
    group_admin_views = "groupadmin,cloud,user,admin"
  }

  lifecycle {
    ignore_changes = [
      template
    ]
  }
}
```

By the way, `delete_on_destruction` is deprecated too since it was causing drift and you should use the [`prevent_destroy`](https://www.terraform.io/language/meta-arguments/lifecycle#prevent_destroy) lifecycle instead.

**Comment by DoomProger** [comment]
Thank you, lifecycle block helps.

Please consider this in the next release, as the [documentation ](https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs/resources/group)does not say anything about this feature.

I think this issue can be closed.
