### ISSUE TITLE
`opennebula_group`: Add `opennebula` section

### ISSUE THREAD

**Issue by frousselet** [OpenNebula/terraform-provider-opennebula#358]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since `template` has been deprecated on `opennebula_group`, `OPENNEBULA` template cannot be set anymore.

### New or Affected Resource(s)

- `opennebula_group`

### Potential Terraform Configuration

```hcl
resource "opennebula_group" "example" {
  # ...

  sunstone = {
    # ...
  }

  opennebula = {
    default_image_persistent_new = true
    # ...
  }
}
```

### References

None

**Comment by treywelsh** [comment]
[The related documentation](https://docs.opennebula.io/6.4/management_and_operations/users_groups_management/manage_groups.html#group-wise-configuration-attributes)

**Comment by treywelsh** [comment]
Deprecating the template field added a bunch of regressions, the goal of this issue is to try fixing one of them: we are not able anymore to pass custom vectors to a template resource. It's why it's now tagged as a bug
