### ISSUE TITLE
`opennebula_group`: Add `template_section` attribute for custom template sections

### ISSUE THREAD

**Issue by frousselet** [OpenNebula/terraform-provider-opennebula#359]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Draft

### New or Affected Resource(s)

- `opennebula_group`

### Potential Terraform Configuration

```hcl
resource "opennebula_group" "example" {
  # ...

  template_section {
    name = "MY_SECTION"
    elements = {
      MY_KEY_1 = "my_value_1",
      MY_KEY_2 = "my_value_2"
    }
  }
}
```

**Comment by treywelsh** [comment]
I should first test each resource dynamic template section behavior: I'm not sure that they all have the exact same behavior regarding key duplication etc.

What should we do if there is several template sections with the same name, return an error or add a filter step based on the `objects` content ?
