### ISSUE TITLE
Timeout provisioning VMs

### ISSUE THREAD

**Issue by turb0steve** [OpenNebula/terraform-provider-opennebula#36]
With larger virtual machine images, or poorly performing storage, the VM instantiation process seems to time-out during the file-copy part of the process at around 3mins.      This seems an extremely short timeout of VM provision (I believe the equivalent in OpenStack and AWS is ~15mins) and causes a terraform apply to fail.   Re-running will, of course, continue successfully as the file has been copied.

Would it be possible to extend the default timeout, or expose it as an argument?

Thanks!

**Comment by jaypif** [comment]
Hi, 

Yes we can extend it of course.
Ideally we can add a param to configure something depending of the usage.

Regards

**Comment by treywelsh** [comment]
The PR is merged, I close the issue. If there is any problem on this part feel free to reopen it or open a new issue.
