### ISSUE TITLE
Uppercase versus lowercase in documentation / unit-tests

### ISSUE THREAD

**Issue by thijsvandergugten** [OpenNebula/terraform-provider-opennebula#364]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/opennebula/opennebula v1.0.1
```

### Affected Resource(s)

Multiple resources may be affected, but at least
- `opennebula_template`

### Terraform Configuration Files

```hcl
resource "opennebula_template" "template" {
  name        = "terra-tpl"
  permissions = "660"
  group       = "oneadmin"
  cpu         = "0.5"
  vcpu        = "1"
  memory      = "512"
  description = "Template created for provider acceptance tests"

  features {
    virtio_scsi_queues = 1
    acpi               = "YES"
  }

  context = {
    DNS_HOSTNAME = "yes"
    NETWORK      = "YES"
  }
}
```

Note that all attributes are written in lowercase, except for `context`. This is consistent with the documentation for [opennebula_template](https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs/resources/template).

### Expected Behavior

Documentation and unit-tests are consistent in uppercase versus lowercase, so it is possible to create a resource via Terraform, and import it without state-differences.

Terraform-state is written in a consistent way, regardless of uppercase/lowercase in the `.tf`-files.

According to the Openebula [documentation](https://docs.opennebula.io/6.4/management_and_operations/references/template.html#syntax) all attribute names are converted to uppercase internally. This means that when an existing resource is imported, it is not known whether the resource was created using uppercase/lowercase attributes.

### Actual Behavior

In for example https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs/resources/template, the field `context` has uppercase-keys, and the field `graphics` has lowercase-keys.

```bash
$ terraform state show opennebula_template.template
# opennebula_template.template:
resource "opennebula_template" "template" {
    context      = {
        "DNS_HOSTNAME" = "yes"
        "NETWORK"      = "YES"
    }
    cpu          = 0.5
    default_tags = {}
    description  = "Template created for provider acceptance tests"
    gid          = 0
    gname        = "oneadmin"
    group        = "oneadmin"
    id           = "633"
    memory       = 512
    name         = "terra-tpl"
    permissions  = "660"
    reg_time     = 1666018161
    tags_all     = {}
    uid          = 0
    uname        = "oneadmin"
    vcpu         = 1

    features {
        acpi               = "YES"
        virtio_scsi_queues = "1"
    }
}
```

Note that Terraform-state is written in the same case as the configuration, with the attribute `context` with uppercase-keys, and with lowercase-keys for other attributes.

```bash
$ sudo onetemplate show 633
TEMPLATE 633 INFORMATION
ID             : 633
NAME           : terra-tpl
USER           : oneadmin
GROUP          : oneadmin
LOCK           : None
REGISTER TIME  : 10/17 14:49:21

PERMISSIONS
OWNER          : um-
GROUP          : um-
OTHER          : ---

TEMPLATE CONTENTS
CONTEXT=[
  DNS_HOSTNAME="yes",
  NETWORK="YES" ]
CPU="0.500000"
DESCRIPTION="Template created for provider acceptance tests"
FEATURES=[
  ACPI="YES",
  VIRTIO_SCSI_QUEUES="1" ]
GRAPHICS=[
  KEYMAP="en-us",
  LISTEN="0.0.0.0",
  TYPE="VNC" ]
MEMORY="512"
OS=[
  ARCH="x86_64",
  BOOT="" ]
VCPU="1"
```

Note that all attributes are in uppercase.

### Steps to Reproduce

1. `terraform apply`
2. `onetemplate show <id>`
3. `terraform state show opennebula_template.template`

**Comment by satyamuralidhar** [comment]
+1

**Comment by thijsvandergugten** [comment]
Please do not close
