### ISSUE TITLE
`opennebula_virtual_network_address_range`: Add support for custom attributes

### ISSUE THREAD

**Issue by TGM** [OpenNebula/terraform-provider-opennebula#376]
Please add support for custom AR attributes.

**Comment by frousselet** [comment]
Hello,

Please follow [CONTRIBUTING.md](https://github.com/OpenNebula/terraform-provider-opennebula/blob/master/CONTRIBUTING.md#issues-and-pull-requests) guidelines for new issues.

By giving some examples of potential Terraform HCL, or links to references you will help us to understand and prioritize your request.

**Comment by TGM** [comment]
When you create a new virtual network you can specify in the address range custom attributes, as well as the IPAM driver.
For the IPAM driver I noticed there is a ticket allready opened https://github.com/OpenNebula/terraform-provider-opennebula/issues/192

For the custom attributes, there is no way to specify them via terraform. This is requires for passing custom attributes to the IPAM driver. Please see the exact fields below.
![custom AR attributes](https://user-images.githubusercontent.com/584882/205890718-eb050aae-026e-4c39-8289-f81de6cfaadc.png)

**Comment by frousselet** [comment]
Ok, thanks for the details.
I can add this to the 1.2.0 milestone alongside #192.

**Comment by TGM** [comment]
Thank you!

**Comment by treywelsh** [comment]
PR submitted in Goca (https://github.com/OpenNebula/one/pull/6055) to allow this change

**Comment by treywelsh** [comment]
EDIT: the PR mentioned in previous comment introduced a regression in Goca, I submitted a new PR to fix this: https://github.com/OpenNebula/one/pull/6104
