### ISSUE TITLE
opennebula_host type=qemu wrong mapping

### ISSUE THREAD

**Issue by TGM** [OpenNebula/terraform-provider-opennebula#385]
OpenNebula version: 6.4.0
terraform-provider-opennebula: 1.1.0

The opennebula_host type= maps the attribute qemu as QEMU, thus making ON unable to recognize the driver.

Plan:
```
  # opennebula_host.example will be created
  + resource "opennebula_host" "example" {
      + cluster_id   = (known after apply)
      + default_tags = (known after apply)
      + id           = (known after apply)
      + name         = "example"
      + tags_all     = (known after apply)
      + type         = "qemu"
    }
```

This is not working as the provider provisions the host with CAPS
![image](https://user-images.githubusercontent.com/584882/208104554-a1372be0-57fb-4fc6-8357-b65536bbe28b.png)

While manually adding a host looks like this
![image](https://user-images.githubusercontent.com/584882/208104458-f96a383b-36e6-4e0f-a7b0-bacfd8516a22.png)

I reached to this conclusion, while using the custom driver.

```
# resource "opennebula_host" "host" {
#   name       = "example"
#   type       = "custom"
#   cluster_id = opennebula_cluster.cluster.id

#   custom {
#     virtualization = "qemu"
#     information    = "qemu"
#   }
# }
```
Witch passes the custom flag as it receives it.

**Comment by mikisvaz** [comment]
I have the same problem, but with 'kvm' turning into 'KVM'

**Comment by mikisvaz** [comment]
I have the same issue but with 'kvm' turning into 'KVM'

**Comment by TGM** [comment]
I can confirm it's working.
