### ISSUE TITLE
Uppercase VM and IM MAD host creating

### ISSUE THREAD

**Issue by evmnaumov** [OpenNebula/terraform-provider-opennebula#394]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.6
on darwin_arm64
+ provider registry.terraform.io/opennebula/opennebula v1.1.0

(on linux installed 1.3.7 - the same problem)

### Affected Resource(s)

- opennebula_host

Create resources:
```
resource "opennebula_host" "some_host1" {
  name       = "10.1.0.94"
  type       = kvm
  cluster_id = 0
}
```

TF plan and apply:

```
  + resource "opennebula_host" "some_host1" {
      + cluster_id   = 0
      + default_tags = (known after apply)
      + id           = (known after apply)
      + name         = "10.1.0.94"
      + tags_all     = (known after apply)
      + type         = "kvm"
    }
```

### Problem:
created host hang on "INIT" state. In host properties I see the IM_MAD and VM_MAD values uppercase "KVM"
After manual changing this values to lowercase "kvm", host becomes "ON"

- #0000

**Comment by TGM** [comment]
Duplicate, will be fixed in 1.1.1 https://github.com/OpenNebula/terraform-provider-opennebula/issues/385 by the same patch that fixes this case.
