### ISSUE TITLE
Can't create untaged network (without VLAN)

### ISSUE THREAD

**Issue by evmnaumov** [OpenNebula/terraform-provider-opennebula#405]
### Terraform Provider Version

Latest (1.1.1)

### Affected Resource(s)

resource_opennebula_virtual_network

### Actual Behavior

Creating network with flag `automatic_vlan_id = false` or `vlan_id = ""` (one of them) returns error:

`You must specify a 'vlan_id' or set the flag 'automatic_vlan_id'`

In web UI I can select parameter "No VLAN network", which creates network with empty VLAN_ID.

### My tf file:

```
resource "opennebula_virtual_network" "public" {
  name            = "public"
  permissions     = "660"
  bridge          = "ovs-br0"
  type            = "ovswitch"
  mtu             = 1500
  network_address = "10.1.0.0"
  network_mask    = "255.255.255.0"
  gateway         = "10.1.0.30"
  dns             = "8.8.8.8"
  security_groups = [0]
  clusters        = [0]
  automatic_vlan_id = false
```

OR

`vlan_id = ""` instead of `automatic_vlan_id = false`

**Comment by treywelsh** [comment]
It's an error returned by the provider that may be wrong in this case.

From the doc: 
- [ovswitch network](https://docs.opennebula.io/6.4/open_cluster_deployment/networking_setup/openvswitch.html#defining-open-vswitch-network)
- [vxlan network](https://docs.opennebula.io/6.4/open_cluster_deployment/networking_setup/vxlan.html#defining-a-vxlan-network)
- [802.1Q network](https://docs.opennebula.io/6.4/open_cluster_deployment/networking_setup/vlan.html#defining-802-1q-network)

VLAND_ID and AUTOMATIC_VLAN_ID are not mandatory for an Open vSwitch network.
