### ISSUE TITLE
virtual machine (ID: 137): unexpected state 'LCM_INIT', wanted target 'RUNNING'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by thangamani-arun** [OpenNebula/terraform-provider-opennebula#410]
We have created 6 numbers of VMs. The errors are random, sometimes you see somes times you won't see. Since It happens quite frequently, logged this report.

### Terraform Version
Terraform v1.3.3

### Affected Resource(s)

+ provider registry.terraform.io/opennebula/opennebula v1.1.1

### Terraform Configuration Files

Create 6 numbers of generic VMs using terraform, you can see this error.

### Expected Behavior

opennebula_virtual_machine.t3-vm1: Creation complete after 1m39s [id=136]
opennebula_virtual_machine.t3-vm2: Creation complete after 1m39s [id=139]
opennebula_virtual_machine.t3-vm4: Creation complete after 1m39s [id=137]

### Actual Behavior
```
│ Error: Failed to wait virtual machine to be in RUNNING state
│
│   with opennebula_virtual_machine.t3-vm1,
│   on vm.tf line 74, in resource "opennebula_virtual_machine" "t3-vm1":
│   74: resource "opennebula_virtual_machine" "t3-vm1" {
│
│ virtual machine (ID: 136): unexpected state 'LCM_INIT', wanted target 'RUNNING'. last error: %!s(<nil>)
╵
╷
│ Error: Failed to wait virtual machine to be in RUNNING state
│
│   with opennebula_virtual_machine.t3-vm2,
│   on vm.tf line 90, in resource "opennebula_virtual_machine" "t3-vm2":
│   90: resource "opennebula_virtual_machine" "t3-vm2" {
│
│ virtual machine (ID: 139): unexpected state 'LCM_INIT', wanted target 'RUNNING'. last error: %!s(<nil>)
╵
╷
│ Error: Failed to wait virtual machine to be in RUNNING state
│
│   with opennebula_virtual_machine.t3-vm4,
│   on vm.tf line 122, in resource "opennebula_virtual_machine" "t3-vm4":
│  122: resource "opennebula_virtual_machine" "t3-vm4" {
│
│ virtual machine (ID: 137): unexpected state 'LCM_INIT', wanted target 'RUNNING'. last error: %!s(<nil>)
```

### Steps to Reproduce

1. `terraform apply`

**Comment by treywelsh** [comment]
Here are the VM states description: https://docs.opennebula.io/6.4/integration_and_development/references/vm_states.html#list-of-states

And the description of the state we're talking about:
`LCM_INIT`: `Internal initialization state, not visible for the end users`

Maybe that I was influenced by the description and I didn't added it to possible transient states when waiting for the VM to be ready, I just opened #411 for this case
