### ISSUE TITLE
Unable to create vms in Pending state

### ISSUE THREAD

**Issue by hbuttguavus** [OpenNebula/terraform-provider-opennebula#43]
Is it possible to have VMs in pending state when they are deployed?

Currently it only looks for the running state even if the vm resource is defined to have pending state when created. Terraform eventually timesout in 3m.

**Comment by jaypif** [comment]
Hi @hbuttguavus 

I can think about adding this in Roadmap ;)

For your information, the provider is now official and the maintenance will continue directly into the official repo: https://github.com/terraform-providers/terraform-provider-opennebula

Would you mind opening this issue on the official repo ?

thank you

**Comment by hbuttguavus** [comment]
of course and thank you!

**Comment by hbuttguavus** [comment]
Moving to the official repo
