### ISSUE TITLE
Support Virtual Network scheduling (NETWORK_MODE = "auto") on virtual machine nics

### ISSUE THREAD

**Issue by jamie-pate** [OpenNebula/terraform-provider-opennebula#477]
### Description

https://docs.opennebula.io/6.2/management_and_operations/capacity_planning/scheduling.html#scheduling-virtual-networks

There is already a `sched_requirements` property on the `opennebula_virtual_machine` and `opennebula_template` definition, so it would make sense to carry this through to the nic structure.

I propose to add a mechanism to enable NETWORK_MODE=auto and other parameters to automatically determine the NIC to attach to a VM and Template.

It could look something like this:

```
nic {
  network_mode = "auto"
  sched_requirements = "TRAFFIC_TYPE = \"public\" "
  sched_rank = "-USED_LEASES"
]
```
  

This would enable automatic nic scheduling for VMs and reduce the terraform resources needed to set up a VM
From the docs:

```
NIC = [ NETWORK_MODE = "auto",
        SCHED_REQUIREMENTS = "TRAFFIC_TYPE = \"public\"",
        SCHED_RANK = "-USED_LEASES" ]
```

### New or affected resources and data sources

`opennebula_virtual_machine` and `opennebula_template`

### Potential terraform configuration

```HCL
resource "opennebula_virtual_machine" "my_vm" {
//...
nic {
  network_mode = "auto"
  sched_requirements = "TRAFFIC_TYPE = \"public\" "
  sched_rank = "-USED_LEASES"
]
}
```

```
resource "opennebula_template" "my_template" {
//...
nic {
  network_mode = "auto"
  sched_requirements = "TRAFFIC_TYPE = \"public\" "
  sched_rank = "-USED_LEASES"
]
}
```
```


### References

https://docs.opennebula.io/6.2/management_and_operations/capacity_planning/scheduling.html#scheduling-virtual-networks
```
NIC = [ NETWORK_MODE = "auto",
        SCHED_REQUIREMENTS = "TRAFFIC_TYPE = \"public\"",
        SCHED_RANK = "-USED_LEASES" ]
```

**Comment by jamie-pate** [comment]
Might be handy for datastores also?

**Comment by treywelsh** [comment]
For the disk with datastore scheduling open an other issue, please.

At first glance:
- this PR has impact on `template` and `virtual_machine` resources: there's several configs to test: when instantiating a VM from a template or when creating a VM from scratch (i.e. a goca dynamic template)
- we may want to modify the `network_id` attribute to make it optional and conflicting with `network_auto`
- NIC update code should be checked carefully.

This will require careful testing regarding the tests cases to cover, the complexity of nic management code etc.
