### ISSUE TITLE
Documentation for tags is confusing

### ISSUE THREAD

**Issue by jamie-pate** [OpenNebula/terraform-provider-opennebula#478]
### Description

In OpenNebula each resource has 'Attributes' which are an arbitrary key/value list which has some special values that affect the resource.

In this terraform provider these are refered to as 'tags'.. but sometimes there is an attribute named 'TAGS' that is documented in the OpenNebula docs.

A line in the provider docs for each `tags` property of each resource/data source would help clarify what these properties do.

### New or affected resources and data sources

data "opennebula_virtual_network"
resource "opennebula_virtualmachine"
Any others that use "tags"

### Potential terraform configuration

```HCL
data "opennebula_virtual_network" "public_network" {
  # tags are actually 'attributes' in the gui
  tags = { labels=var.public_network_label }
}
```

### References

https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs/data-sources/virtual_network#tags
https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs/resources/virtual_machine#tags
https://docs.opennebula.io/5.12/search.html?q=TAGS&check_keywords=yes&area=default

**Comment by frousselet** [comment]
Hello @jamie-pate,
I just created a PR where I update the documentation. Please let me know if it's more clear.

**Comment by jamie-pate** [comment]
Looks good to me :+1:
