### ISSUE TITLE
Data Source `opennebula_template`: broken name query

### ISSUE THREAD

**Issue by TGM** [OpenNebula/terraform-provider-opennebula#479]
### Description

Release v1.3.0 needs a review.

data resource opennebula_template breaks the name query.

### Terraform and Provider version

```
terraform -v
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/opennebula/opennebula v1.3.0
```

### Affected resources and data sources

data opennebula_template

### Terraform configuration

```HCL
# Provider configuration
terraform {
  required_providers {
    opennebula = {
      source  = "OpenNebula/opennebula"
      version = "~> 1.2"
    }
  }
}


data "opennebula_template" "template" {
  name = "rocky_8.7"
}

output "debug" {
  value = data.opennebula_template.template
}

```
```


### Expected behavior

Should have return the template details.

The template is in place.
![image](https://github.com/OpenNebula/terraform-provider-opennebula/assets/584882/70d746a9-fb3b-4e70-a348-fe764c47e854)


### Actual behavior

```
erraform plan
data.opennebula_template.template: Reading...
╷
│ Error: templates filtering failed
│ 
│   with data.opennebula_template.template,
│   on main.tf line 17, in data "opennebula_template" "template":
│   17: data "opennebula_template" "template" {
│ 
│ no templates match the constraints
╵
root@danc-laptop:~/dev/repos/terraform/iaas/tftest# terraform -v
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/opennebula/opennebula v1.3.0

Your version of Terraform is out of date! The latest version
is 1.5.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Steps to Reproduce

Query a data source with opennebula_template.

### Debug output

_No response_

### Panic output

_No response_

### Important factoids

_No response_

### References

_No response_

**Comment by evmnaumov** [comment]
Also have problem on 1.3.0 version

```
data "opennebula_template" "debian11" {
  name = "Debian 11"
}
``` 

during plan have an error:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: templates filtering failed
│ 
│   with data.opennebula_template.debian11,
│   on datasources.tf line 5, in data "opennebula_template" "debian11":
│    5: data "opennebula_template" "debian11" {
│ 
│ no templates match the constraints
``` 

On 1.2.1 works fine.
