### ISSUE TITLE
Unable to supply credentials using OPENNEBULA_USERNAME and OPENNEBULA_PASSWORD environment variables 

### ISSUE THREAD

**Issue by jamie-pate** [OpenNebula/terraform-provider-opennebula#501]
### Description

The documentation says that we should be able to pass username and password using environment variables:

https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs#environment-variables

But the `username` and `password` fields are required in 1.3.1 and 

### Terraform and Provider version

Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/opennebula/opennebula v1.3.1

### Affected resources and data sources

provider

### Terraform configuration

```HCL
provider "opennebula" {
  endpoint      = var.one.endpoint
  flow_endpoint = var.one.flow_endpoint
}
```

### Expected behavior

As documented I expect to be able to omit the `username` and `password` fields in the provider configuration and have the provider read them from the environment.

### Actual behavior

These properties are required, and if they are blank then the provider throws an error:

```
╷
│ Error: username should be defined
│ 
│   with provider["registry.terraform.io/opennebula/opennebula"],
│   on main.tf line 64, in provider "opennebula":
│   64: provider "opennebula" {
│ 
╵
```

```
│ Error: password should be defined
│ 
│   with provider["registry.terraform.io/opennebula/opennebula"],
│   on main.tf line 64, in provider "opennebula":
│   64: provider "opennebula" {
│ 
```

### Steps to Reproduce

Create a configuration and try to use `OPENNEBULA_USERNAME` and `OPENNEBULA_PASSWORD` following the [documentation](https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs#environment-variables)

### References

https://registry.terraform.io/providers/OpenNebula/opennebula/latest/docs#environment-variables
https://github.com/OpenNebula/terraform-provider-opennebula/issues/121#issuecomment-1112159627

**Comment by jamie-pate** [comment]
Afaik this is still an issue?

**Comment by jamie-pate** [comment]
not fixing itself.. 30 days seems really short for 'stale'

**Comment by frousselet** [comment]
Hello @jamie-pate,

How do you export both variables? Tried on my side and I get it working properly.

**Comment by jamie-pate** [comment]
> How do you export both variables?

using `export OPENNEBULA_USER=value` and `export OPENNEBULA_PASSWORD=value`.. how else?

```
terraform {
  required_version = ">= 1.12.2"
  required_providers {
    opennebula = {
      source  = "OpenNebula/opennebula"
      version = "1.5.0"
    }
}
provider "opennebula" {
  endpoint      = var.one.endpoint
  flow_endpoint = var.one.flow_endpoint
}
```

```
$ echo $OPENNEBULA_USER
jpate
$ echo $OPENNEBULA_PASSWORD
56875xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2
$ terraform plan
provider.opennebula.username
  The ID of the user to identify as

  Enter a value: 
```
