### ISSUE TITLE
How to set the owner of a virtual network?

### ISSUE THREAD

**Issue by stenub** [OpenNebula/terraform-provider-opennebula#529]
### Question

when creating a new virtual network as oneadmin, i want to set the user and the group to a freshly created user and group. I managed to set the group, but when looking at the documentation i can find no way to set the virtual network owner. Is this not implemented? In Sunstone this is easily possible, but the provider lacks this feature (still?), right?

**Comment by treywelsh** [comment]
You're right it's missing in the provider and it may be missing for a bunch of other resources.
I just opened #531, not tested yet, feel free to give it a try (building the provider from the branch) a drop a comment

**Comment by al-lac** [comment]
Would be great to have this

**Comment by treywelsh** [comment]
I quickly tested the PR, seems good.
However it's done only for virtual network according to the scope of the current issue
