### ISSUE TITLE
Problem with 'context' block in OpenNebula template resource

### ISSUE THREAD

**Issue by llakssz** [OpenNebula/terraform-provider-opennebula#56]
When trying to use the `context` block in a OpenNebula template resource, it returns with an error. From what I understand, this should be a new feature added in 0.2.0/0.2.1, so I'm confused as to why this is happening.
https://www.terraform.io/docs/providers/opennebula/r/template.html#context

When running `terraform plan`:
``` 
Error: Unsupported block type

  on main.tf line 72, in resource "opennebula_template" "nginx_template":
  72:  context {

Blocks of type "context" are not expected here. Did you mean to define argument "context"? If so, use the equals sign to assign it a value.
```

Extract from main.tf file:
```
resource "opennebula_template" "nginx_template" {
  name = "nginx_template"
  cpu = 4
  memory = 4096
  group = "terraform"
  permissions = "660"

 context {
     NETWORK = "YES"
     HOSTNAME = "hostname"
     USERNAME = "username"
 }

  graphics {
    type = "VNC"
    listen = "0.0.0.0"
  }

  os {
    arch = "x86_64"
    boot = ""
  }

 ...

}
```

Output of `terraform -v`:
```
Terraform v0.12.28
+ provider.opennebula v0.2.1
```

If any more detail is needed let me know, thanks for all the work!

**Comment by treywelsh** [comment]
Hi,

As you can see in [VM test code here](https://github.com/terraform-providers/terraform-provider-opennebula/blob/master/opennebula/resource_opennebula_virtual_machine_test.go#L228) there is an equal sign: `context = {`.
This is also what the error you get reports, to write the equal sign.

There is no equal sign on the terraform page so this may be a documentation issue.

Sorry to not give you more details I don't know HCL syntax in depth :)

**Comment by llakssz** [comment]
From reading the error message, I had thought that providing `=` in the HCL file would change the behavior of `context` and not give the desired outcome. I too do not fully understand HCL syntax, so maybe that adds to my confusion, so don't worry and thank you for the help!

Is the documentation the problem (not including the `=`), or is the implementation the problem (requires the `=`)?
Is there a reason why all the other blocks (`graphics`, `disk`, `nic`...) do not require a `=` but `context` does? (and `tags`, I notice, from your test code link)

**Comment by benendboss** [comment]
In the example on the terraform-opennebula [doku](https://www.terraform.io/docs/providers/opennebula/r/virtual_machine.html) there is '=' missing for context block.

**Comment by christian7007** [comment]
It seems that omitting the `=` sign for defining attributes was supported until Terraform v0.12.0: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#configuration-syntax-changes.
