### ISSUE TITLE
Improve contribution guidelines

### ISSUE THREAD

**Issue by Thiryn** [OpenNebula/terraform-provider-opennebula#568]
### Description

The contribution guidelines could be improved, as the current guidelines allow to install the provider locally entirely, entering the provider binary hash in the `.terraform.lock.hcl` which changes at every build. Terraform allows for `dev_override` for the specific use case of developing a provider, enabling to change the provider without touching the user terraform code.

### New or affected resources and data sources

none

### Potential terraform configuration

```HCL
none
```

### References

https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers

**Comment by frousselet** [comment]
Hello @Thiryn,

That's interesting, I was not aware of this.
Many thanks.
