### ISSUE TITLE
Zone support 

### ISSUE THREAD

**Issue by jaypif** [OpenNebula/terraform-provider-opennebula#58]
In case there are several zone on OpenNebula cluster it should be nice to support several zones (they must be part of an OpenNebula federation)

**Comment by treywelsh** [comment]
[See the alias meta argument](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations) already available in terraform.
It allows to manage multiprovider configuration, so, with one configuration per zone this mechanisms could be used to manage resources across several zones.
