### ISSUE TITLE
allow to lock ressources

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#65]
To prevent accidental operations like resource deletion, [OpenNebula allow to lock resources](https://docs.opennebula.io/5.12/operation/users_groups_management/chmod.html#locking-resources).

We could enable this in terraform via a new schema argument, and lock ressource at creation (or only via updates).
Then to destroy a locked ressource this should done in two steps:
1. a first apply to unlock the ressource
2. destroy

**Comment by jaypif** [comment]
Lock is already implemented for some resources

**Comment by treywelsh** [comment]
Indeed, lock management is implemented in the provider only for `image` resource.

Locking is available in OpenNebula for these resources:
- managed by the provider: VM, NET, TEMPLATE
- not managed by the provider: DOCUMENT, VROUTER, MARKETPLACEAPP
