### ISSUE TITLE
Not possible to use provider from Terraform Registry 

### ISSUE THREAD

**Issue by aaachuang** [OpenNebula/terraform-provider-opennebula#81]
ran terraform 0.13.5 with required_providers source = "opennebula/openebula" failed. however it works with  terraform-providers/opennebula although with warning.

---

Initializing the backend...

Initializing provider plugins...
- Finding latest version of opennebula/opennebula...

Error: Failed to install provider

Error while installing opennebula/opennebula v0.2.2: provider
registry.terraform.io/opennebula/opennebula 0.2.2 is not available for
linux_amd64

---
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "opennebula" (terraform-providers/opennebula) 0.2.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.opennebula: version = "~> 0.2"

Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to OpenNebula/opennebula. Please update your source in required_providers.

**Comment by jaypif** [comment]
Hi,

Can you share the terraform file with the block calling the `required_provider` ?

This should looks like this:
```
terraform {
  required_providers {
    opennebula = {
      source = "OpenNebula/opennebula"
      version = "0.2.2"
    }
  }
}
```

Thanks and sorry for the inconvenience

**Comment by aaachuang** [comment]
terraform {
  required_version = ">= 0.13"
  required_providers {
    opennebula = {
      //  broken
      //source = "OpenNebula/opennebula"
      source = "terraform-providers/opennebula"
    }
  }
}

**Comment by jaypif** [comment]
same issue with Mac OSX users.
```
registry.terraform.io/opennebula/opennebula 0.2.2 is not available for
darwin_amd64
```

**Comment by jaypif** [comment]
Hi,

After exchanges with Hashicorp a new 0.2.2 has been built and is now available on the Terraform registry.

I consider this issue as solved
