### ISSUE TITLE
Incompatible with OSX

### ISSUE THREAD

**Issue by spuder** [OpenNebula/terraform-provider-opennebula#84]
Terraform version = 0.13.5

When I try and use this provider on osx, I get this error

```
variable "one_endpoint" {}
variable "one_username" {}
variable "one_password" {}

provider "opennebula" {
  endpoint = var.one_endpoint
  username = var.one_username
  password = var.one_password
}

# Create a new group of users to the OpenNebula cluster
resource "opennebula_group" "group" {
  # ...
}
```
```
terraform init
Initializing the backend...

Initializing provider plugins...
- Finding latest version of opennebula/opennebula...

Error: Failed to install provider

Error while installing opennebula/opennebula v0.2.2: provider
registry.terraform.io/opennebula/opennebula 0.2.2 is not available for
darwin_amd64
```

**Comment by jaypif** [comment]
Hi,


This is the same issue than #81 
Actually, the provider is not well published on the Terraform Registry. It does not work for any platform.

Sorry about the inconvenience. We are working on it with Terraform team.

I invite you to use the workaround from @aaachuang (#81) until a correct release is published on the registry

I close this issue, all updates will be performed on #81.

Regards
