### ISSUE TITLE
CPU Model while using opennebula_virtual_machine

### ISSUE THREAD

**Issue by ankur-gupta-guavus** [OpenNebula/terraform-provider-opennebula#98]
Hey guys I was wondering how can we specify CPU MODEL while using opennebula_virtual_machine . Can you please helo with the same ?

**Comment by jaypif** [comment]
Hi @ankur-gupta-guavus 

Unfortunately it is not available yet. It could be added as a new feature. It will look like "os" or "graphics" section.

**Comment by ankur-gupta-guavus** [comment]
@jaypif Can you please check following [PR](https://github.com/OpenNebula/terraform-provider-opennebula/pull/99)

**Comment by treywelsh** [comment]
PR #103 merged
